const systems = [{
  id: '953fe62f-da6e-4dc5-b55a-5e216ab78bb5',
  color: 'The Legend of Zelda 25th Anniversary (Cosmo Black)',
  description: '3DS',
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '139d6b7e-5250-4c19-b171-d16e3e9d3715',
  color: 'The Legend of Zelda: A Link Between Worlds (Gold)',
  description: '3DS XL',
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'a5010a2a-d51d-4988-8447-95c3e22d97d3',
  color: 'Black x Turquoise',
  description: 'New 2DS XL',
  borrowedInFrom: '',
  borrowedOutTo: '',
}]

const cables = ['Charger x3']

const accessories = ['3DS XL Charger Holster']

const controllers = []

const games = [{
  id: 'a9a75e6c-d3f5-4bf1-9073-7f5ed7912918',
  name: 'Animal Crossing: New Leaf',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Animal_Crossing:_New_Leaf',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: true,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'fcb4152b-099b-49c7-bd4c-cc218a7710af',
  name: 'Bravely Default: Flying Fairy',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Bravely_Default',
  price: 0,
  extras: [],
  played: true,
  completed: true,
  favourite: true,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '5caba431-bceb-4459-89d6-a980418f56e1',
  name: 'Bravely Second: End Layer',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Bravely_Second:_End_Layer',
  price: 0,
  extras: [],
  played: true,
  completed: true,
  favourite: true,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'f51fefff-8da4-4712-95e1-e00caac2f718',
  name: 'Conception II: Children of the Seven Stars',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Conception_II:_Children_of_the_Seven_Stars',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '7db4e5ab-2d8a-48f9-9ce0-944cc01425c4',
  name: 'Etrian Mystery Dungeon',
  receiptLocation: '^?',
  url: 'https://en.wikipedia.org/wiki/Etrian_Mystery_Dungeon',
  price: 0,
  extras: [],
  played: true,
  completed: true,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '36253a87-43ad-4572-ad4b-512653950c87',
  name: 'Etrian Odyssey Untold: The Millennium Girl',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Etrian_Odyssey_Untold:_The_Millennium_Girl',
  price: 0,
  extras: [],
  played: true,
  completed: true,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '90a312a7-1b7b-4014-924e-333e45211e90',
  name: 'Etrian Odyssey 2 Untold: The Fafnir Knight',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Etrian_Odyssey_2_Untold:_The_Fafnir_Knight',
  price: 0,
  extras: [],
  played: true,
  completed: true,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'a2a47a11-fab4-4133-93ac-3fbf03143f66',
  name: 'Etrian Odyssey IV: Legends of the Titan',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Etrian_Odyssey_IV',
  price: 0,
  extras: [],
  played: true,
  completed: true,
  favourite: true,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '5dfa13d5-1d12-4d34-b092-117d1c9fe5ce',
  name: 'Etrian Odyssey V: Beyond the Myth',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Etrian_Odyssey_V',
  price: 0,
  extras: [],
  played: true,
  completed: true,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'abf2dfba-fb09-42ee-85e1-7887eee74163',
  name: 'Fire Emblem: Awakening',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Fire_Emblem_Awakening',
  price: 0,
  extras: [],
  played: true,
  completed: true,
  favourite: true,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '93800c42-2b16-4738-9bd0-7534c9837ec3',
  name: 'Fire Emblem Echoes: Shadows of Valentia',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Fire_Emblem_Echoes:_Shadows_of_Valentia',
  price: 0,
  extras: [],
  played: true,
  completed: true,
  favourite: true,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'c6735dc2-69b5-4ec5-99b9-cd5a5edbcbba',
  name: 'Fire Emblem Fates: Birthright',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Fire_Emblem_Fates',
  price: 0,
  extras: [],
  played: true,
  completed: true,
  favourite: true,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '88cd784d-ec7d-456e-a6ba-13bcba4463e5',
  name: 'Fire Emblem Fates: Conquest',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Fire_Emblem_Fates',
  price: 0,
  extras: [],
  played: true,
  completed: true,
  favourite: true,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '336bc3f9-a090-4f1b-9aec-bcce08f02e70',
  name: 'Fire Emblem Fates: Revelation',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Fire_Emblem_Fates',
  price: 0,
  extras: [],
  played: true,
  completed: true,
  favourite: true,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'cce89e46-142b-4b59-a313-d2f6f09154c7',
  name: 'Harvest Moon: The Lost Valley',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Harvest_Moon:_The_Lost_Valley',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'ddd954d4-28b9-4e0b-a744-a66fe0e2f5b7',
  name: 'Pokemon Y',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Pok%C3%A9mon_X_and_Y',
  price: 0,
  extras: [],
  played: true,
  completed: true,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '4335dba4-3206-483a-8acc-10b20eccd87e',
  name: 'Pokemon Alpha Sapphire',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Pok%C3%A9mon_Omega_Ruby_and_Alpha_Sapphire',
  price: 0,
  extras: [],
  played: true,
  completed: true,
  favourite: true,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'be25834c-fd58-4df8-ac3f-f0ba81a3d262',
  name: 'Project X Zone',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Project_X_Zone',
  price: 0,
  extras: [],
  played: true,
  completed: true,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '4c717d89-8cf4-44d9-beb1-b50701a8509a',
  name: 'Project X Zone 2',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Project_X_Zone_2',
  price: 0,
  extras: [],
  played: true,
  completed: true,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '79133828-e2ea-46f1-87fd-46cac41668cc',
  name: 'Shin Megami Tensei: Devil Survivor Overclocked',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Shin_Megami_Tensei:_Devil_Survivor#Remake',
  price: 0,
  extras: [],
  played: true,
  completed: true,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '8339dadf-4740-4ff0-9a2b-12122975d058',
  name: 'Shin Megami Tensei: Devil Survivor 2 Record Breaker',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Shin_Megami_Tensei:_Devil_Survivor_2#Remake',
  price: 0,
  extras: [],
  played: true,
  completed: true,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'bcd581dd-1c02-4340-8867-97b64e43ada5',
  name: 'Shin Megami Tensei IV',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Shin_Megami_Tensei_IV',
  price: 0,
  extras: [],
  played: true,
  completed: true,
  favourite: true,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'edb8cd68-807d-4c24-b38b-795b7db056f1',
  name: 'Shin Megami Tensei: Strange Journey Redux',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Shin_Megami_Tensei:_Strange_Journey',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '82e66635-53df-4f9f-af2b-716d26f78971',
  name: 'Starfox 64 3D',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Star_Fox_64_3D',
  price: 0,
  extras: [],
  played: true,
  completed: true,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '33369301-4d0f-47c4-b7ab-1eb53097be13',
  name: 'Super Smash Bros. 4 3DS',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Super_Smash_Bros._for_Nintendo_3DS_and_Wii_U',
  price: 0,
  extras: [],
  played: true,
  completed: true,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '99e9eeca-8f77-485d-b921-aefaab96f1f0',
  name: 'Tales of the Abyss',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Tales_of_the_Abyss#3DS_version',
  price: 0,
  extras: [],
  played: true,
  completed: true,
  favourite: true,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'b4470c82-563c-4d72-8a61-00750e09b2f1',
  name: 'The Legend of Zelda: Ocarina of Time 3D',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/The_Legend_of_Zelda:_Ocarina_of_Time_3D',
  price: 0,
  extras: [],
  played: true,
  completed: true,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '2f4f118b-c8e7-47e8-9c05-4c41a003368a',
  name: 'The Legend of Zelda: Majora\'s Mask 3D',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/The_Legend_of_Zelda:_Majora%27s_Mask_3D',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'ca2bb418-b78e-47e6-abbf-d39d92809b75',
  name: 'Zero Escape: Virtue\'s Last Reward',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Zero_Escape:_Virtue%27s_Last_Reward',
  price: 0,
  extras: [],
  played: true,
  completed: true,
  favourite: true,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'e4d1a45c-eda3-48c2-add2-a9887c111d62',
  name: 'Zero Time Dilemma',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Zero_Time_Dilemma',
  price: 0,
  extras: [],
  played: true,
  completed: true,
  favourite: true,
  borrowedInFrom: '',
  borrowedOutTo: '',
}]

export default {
  id: '12b38fee-9315-450e-ad80-33c0473c439c',
  name: '3DS',
  systems,
  cables,
  accessories,
  controllers,
  games,
}
