const systems = [{
  id: '2ad6ef1d-a841-451e-8124-7503fa0fd4d5',
  color: 'White',
  description: '',
  borrowedInFrom: '',
  borrowedOutTo: '',
}]

const cables = ['Power', 'AV']

const accessories = []

const controllers = ['Standard (White)', 'Transparent Red']

const games = [{
  id: '19c4f66c-0231-4c70-b91a-03cdba36ded5',
  name: 'ChuChu Rocket!',
  receiptLocation: '(Toyratt)',
  url: 'https://en.wikipedia.org/wiki/ChuChu_Rocket!',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '174dc6fa-291c-4d3f-bffd-e1ce7a8ac7a6',
  name: 'Grandia II',
  receiptLocation: '(Toyratt)',
  url: 'https://en.wikipedia.org/wiki/Grandia_II',
  price: 0,
  extras: [],
  played: true,
  completed: true,
  favourite: true,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'd8e2f111-0e0c-4e98-9e80-1caf4553ede3',
  name: 'Jet Grind Radio',
  receiptLocation: 'Grandia',
  url: 'https://en.wikipedia.org/wiki/Jet_Set_Radio',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'cbfde6a1-de64-4555-b9cb-94f726e226c6',
  name: 'Legacy of Kain: Soul Reaver',
  receiptLocation: 'Grandia',
  url: 'https://en.wikipedia.org/wiki/Legacy_of_Kain:_Soul_Reaver',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'efad492e-2618-44f2-aa64-23e3f980c243',
  name: 'Marvel vs. Capcom: Clash of Super Heroes',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Marvel_vs._Capcom:_Clash_of_Super_Heroes',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '131aa32f-d635-4704-a693-78e07b96a9b0',
  name: 'Power Stone',
  receiptLocation: 'Grandia',
  url: 'https://en.wikipedia.org/wiki/Power_Stone',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'b83d5e81-c5a1-4e2a-89fc-43da0df9cc8e',
  name: 'Skies of Arcadia',
  receiptLocation: 'Marvel vs. Capcom: Clash of Super Heroes',
  url: 'https://en.wikipedia.org/wiki/Skies_of_Arcadia',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '6481e77d-d7d5-4df0-9d7c-854c353943a8',
  name: 'Sonic Adventure Limited Edition',
  receiptLocation: 'Marvel vs. Capcom: Clash of Super Heroes',
  url: 'https://en.wikipedia.org/wiki/Sonic_Adventure',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'db08518a-5f05-44b4-b66e-87d07717ff45',
  name: 'Sonic Adventure 2',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Sonic_Adventure_2',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '978b17f4-d6c4-45db-9aa7-6297ed399f12',
  name: 'Soul Calibur',
  receiptLocation: 'Sonic Adventure 2',
  url: 'https://en.wikipedia.org/wiki/Soulcalibur_(video_game)',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'e86068bc-26ff-4d1d-98d6-b90a23552254',
  name: 'Soul Calibur (Japanese)',
  receiptLocation: 'Marvel vs. Capcom: Clash of Super Heroes',
  url: 'https://en.wikipedia.org/wiki/Soulcalibur_(video_game)',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '351c18c1-b5e6-4635-be98-af27f65e4a19',
  name: 'Worms Armageddon',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Worms_Armageddon',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}]

export default {
  id: '37ac7333-b2ec-4748-bf59-d263200cf9a0',
  name: 'Dreamcast',
  index: 15,
  systems,
  cables,
  accessories,
  controllers,
  games,
}
