const systems = [{
  id: '22b17f00-1dd3-446c-90b5-2044d7cd2a30',
  color: 'Teal',
  description: 'DS',
  borrowedInFrom: 'Max',
  borrowedOutTo: '',
}, {
  id: 'd8e5c3e5-551e-4d49-9e98-b96463f5dc28',
  color: 'Electric Blue',
  description: 'DS',
  borrowedInFrom: 'Matt',
  borrowedOutTo: '',
}, {
  id: 'd53aba02-d902-430d-a7cb-f83dbb350c80',
  color: 'Crystal White',
  description: 'DS Lite',
  borrowedInFrom: 'Kassandra',
  borrowedOutTo: '',
}, {
  id: '4b36e113-fcf1-467f-b146-eb2ff5a71942',
  color: 'Onyx Black',
  description: 'DS Lite',
  borrowedInFrom: 'Kristen',
  borrowedOutTo: '',
}]

const cables = ['Charger (DS) x2', 'Charger (DS Lite)']

const accessories = ['Action Replay']

const controllers = []

const games = [{
  id: 'e10c8c59-4bde-4409-8490-23422040845c',
  name: 'Animal Crossing: Wild World',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Animal_Crossing:_Wild_World',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: 'Max',
  borrowedOutTo: '',
}, {
  id: 'f16c2149-008d-460f-a94f-ec575255f375',
  name: 'Children of Mana',
  receiptLocation: 'Wild Arms',
  url: 'https://en.wikipedia.org/wiki/Children_of_Mana',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: true,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '07c0377e-a1a6-4330-bc48-58c4c2a27839',
  name: 'Chrono Trigger',
  receiptLocation: 'Disgaea: Afternoon of Darkness',
  url: 'https://en.wikipedia.org/wiki/Chrono_Trigger#Nintendo_DS',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '8b93f63e-7899-4705-8b07-e0f822e8fa10',
  name: 'Diddy Kong Racing DS',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Diddy_Kong_Racing#Remake',
  price: 0,
  tags: [],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '2880760c-ec12-4444-9f7f-9080cc7a890f',
  name: 'Dragon Quest V: Hand of the Heavenly Bride',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Dragon_Quest_V#Nintendo_DS_remake',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: true,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '4083fc48-c240-4fcb-9819-c3b983104e15',
  name: 'Dragon Quest VI: Realms of Revelation',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Dragon_Quest_VI#Nintendo_DS_remake',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: 'Max',
  borrowedOutTo: '',
}, {
  id: '9e43bf62-3ca4-4828-9383-24a603aaca39',
  name: 'Dragon Quest IX: Sentinels of the Starry Skies',
  receiptLocation: 'Golden Sun: Dark Dawn',
  url: 'https://en.wikipedia.org/wiki/Dragon_Quest_IX',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: true,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '908cd7c8-6d45-4dae-97e0-1adbc25844c8',
  name: 'Etrian Odyssey II: Heroes of Lagaard',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Etrian_Odyssey_II',
  price: 0,
  tags: [],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'b5b1d7d3-72ab-4fcb-ba69-21aa0ce4622e',
  name: 'Final Fantasy III',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Final_Fantasy_III#3D_remake',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '33670674-41e7-44fb-9787-707741799ac9',
  name: 'Final Fantasy IV',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Final_Fantasy_IV_(2007_video_game)',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: true,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '41a2371f-bcb9-4c8b-a9d6-e88b944fbdaf',
  name: 'Final Fantasy XII: Revenant Wings',
  receiptLocation: 'Mega Man X7',
  url: 'https://en.wikipedia.org/wiki/Final_Fantasy_XII:_Revenant_Wings',
  price: 0,
  tags: [],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '755bc941-a258-4722-a6af-85e19c307d7a',
  name: 'Final Fantasy Tactics A2: Grimoire of the Rift',
  receiptLocation: 'Wild Arms',
  url: 'https://en.wikipedia.org/wiki/Final_Fantasy_Tactics_A2:_Grimoire_of_the_Rift',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: true,
  favourite: true,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '803dbb56-6942-403d-8442-8c5a93d68b52',
  name: 'Final Fantasy: The 4 Heroes of Light',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Final_Fantasy:_The_4_Heroes_of_Light',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '653df655-2a03-4f05-96af-a24629106c73',
  name: 'Fire Emblem: Shadow Dragon',
  receiptLocation: 'Fire Emblem Echoes: Shadows of Valentia',
  url: 'https://en.wikipedia.org/wiki/Fire_Emblem:_Shadow_Dragon',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: true,
  favourite: true,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '3d4e6ffa-e7cb-4354-bc57-42e0ef1448d5',
  name: 'Golden Sun: Dark Dawn',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Golden_Sun:_Dark_Dawn',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: true,
  favourite: true,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '0699bc64-4f58-44ef-a98a-a8dc71f5996b',
  name: 'Harvest Moon DS',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Harvest_Moon_DS',
  price: 0,
  tags: [],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'b6be73a4-a5a9-40be-a999-8b077c5bb47e',
  name: 'Heroes of Mana',
  receiptLocation: 'Sakura Wars: So Long, My Love',
  url: 'https://en.wikipedia.org/wiki/Heroes_of_Mana',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'e166d41e-c063-4885-b00d-f9dc498927d2',
  name: 'Kirby Super Star Ultra',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Kirby_Super_Star#Remake',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '600c661c-daa3-45f1-9ab3-f812b8f68bbc',
  name: 'The Legend of Zelda: Phantom Hourglass',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/The_Legend_of_Zelda:_Phantom_Hourglass',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '9b782d9e-2c48-4a70-b0fc-81c1957ad671',
  name: 'The Legend of Zelda: Spirit Tracks',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/The_Legend_of_Zelda:_Spirit_Tracks',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'da1f0b12-d572-46a7-8ae6-58082eebec27',
  name: 'Mario & Luigi: Bowser\'s Inside Story',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Mario_%26_Luigi:_Bowser%27s_Inside_Story',
  price: 0,
  tags: [],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: 'Max',
  borrowedOutTo: '',
}, {
  id: '46367ccc-ff0a-4e85-9f15-6185e6a44330',
  name: 'Metroid Prime Hunters',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Metroid_Prime_Hunters',
  price: 0,
  tags: [],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '693a3d71-8945-4477-8f4c-6f73d9e93d11',
  name: 'Nine Hours, Nine Persons, Nine Doors',
  receiptLocation: '(Mac Game Guy)',
  url: 'https://en.wikipedia.org/wiki/Nine_Hours,_Nine_Persons,_Nine_Doors',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: true,
  favourite: true,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'cda14082-e477-4f4b-8b4f-0db673fb2f3f',
  name: 'Nintendogs: Chihuahua & Friends',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Nintendogs',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: 'Kristen',
  borrowedOutTo: '',
}, {
  id: '5b65fa9a-42ce-4664-9f8d-773d1f543fdf',
  name: 'Pokemon Diamond',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Pok%C3%A9mon_Diamond_and_Pearl',
  price: 0,
  tags: [],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: 'Max',
  borrowedOutTo: '',
}, {
  id: 'f47bbf33-c3f9-4c67-8d74-5ac189bcada2',
  name: 'Pokemon Mystery Dungeon: Explorers of Time',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Pok%C3%A9mon_Mystery_Dungeon:_Explorers_of_Time_and_Explorers_of_Darkness',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: 'Max',
  borrowedOutTo: '',
}, {
  id: 'c2431fa3-073c-4173-8ac6-1be5b73c56ce',
  name: 'Pokemon Platinum',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Pok%C3%A9mon_Platinum',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: true,
  favourite: true,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '58be6d81-4099-4240-9104-04f70d99c985',
  name: 'Pokemon SoulSilver',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Pok%C3%A9mon_HeartGold_and_SoulSilver',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: true,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '3cfd558f-a4a0-4ebf-8434-7c20b835d8a2',
  name: 'Pokemon White',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Pok%C3%A9mon_Black_and_White',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: true,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'ef6ec2d2-ba29-44e9-8829-3758e112609f',
  name: 'Pokemon White 2',
  receiptLocation: 'Heavy Rain',
  url: 'https://en.wikipedia.org/wiki/Pok%C3%A9mon_Black_2_and_White_2',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: true,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '881dfe2c-a30b-46d7-a464-46f02cbd628f',
  name: 'Pokemon Conquest',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Pok%C3%A9mon_Conquest',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '1bd8d900-30c2-4e35-a2ff-611b8c45b70f',
  name: 'Radiant Historia',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Radiant_Historia',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '3f70717a-40f0-47b5-adb8-a0c039962621',
  name: 'Shin Megami Tensei: Devil Survivor 2',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Shin_Megami_Tensei:_Devil_Survivor_2',
  price: 0,
  tags: [],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '979233cf-faa2-4fbd-a27c-eda7c900cf7f',
  name: 'Suikoden Tierkreis',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Suikoden_Tierkreis',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: true,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '0dff7313-d7f7-4f12-b28e-ea3481567d04',
  name: 'Tales of the Tempest',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Tales_of_the_Tempest',
  price: 0,
  tags: [],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'a0ad8bff-4f9d-46d5-957c-6707b7ea74ac',
  name: 'The World Ends with You',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/The_World_Ends_with_You',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: true,
  favourite: true,
  borrowedInFrom: '',
  borrowedOutTo: '',
}]

export default {
  id: '4ad042aa-640b-4437-ba55-0a7226901ba3',
  name: 'DS',
  index: 8,
  systems,
  cables,
  accessories,
  controllers,
  games,
}
