const systems = [{
  id: 'cbcc2a46-9519-4202-b67a-53273adee168',
  color: 'White',
  description: '',
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '99cc6b51-9821-49d9-8cff-07aa8511f512',
  color: 'Indigo',
  description: '',
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'c134cca9-7e4a-4ada-989d-af293c91eba2',
  color: 'Red',
  description: 'Game Boy Advance SP',
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'ae50b096-c551-4e27-b936-56869e841b93',
  color: 'Silver',
  description: 'Game Boy Advance SP (broken)',
  borrowedInFrom: '',
  borrowedOutTo: '',
}]

const cables = ['Charger x2']

const accessories = ['Link x2']

const controllers = []

const games = [{
  id: '4f1aa248-6953-4872-9c25-2b8738f40f6f',
  name: '007 Everything or Nothing',
  receiptLocation: 'Dragon Ball Z: Budokai 2',
  url: 'https://en.wikipedia.org/wiki/James_Bond_007:_Everything_or_Nothing',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '16ad4116-eff1-42c0-9e69-4e12d000788d',
  name: 'Banjo Kazooie: Grunty\'s Revenge',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Banjo-Kazooie:_Grunty%27s_Revenge',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'd5acb5ce-539d-48a3-b9e9-28b2831c898e',
  name: 'Banjo Pilot',
  receiptLocation: 'Final Fantasy X',
  url: 'https://en.wikipedia.org/wiki/Banjo-Pilot',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '64bb1e93-06c3-490c-bad7-cf8f93019573',
  name: 'Breath of Fire',
  receiptLocation: 'Suikoden IV',
  url: 'https://en.wikipedia.org/wiki/Breath_of_Fire_(video_game)',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'c2d4f632-5226-442e-b160-0011b8a6c8ae',
  name: 'Castlevania: Circle of the Moon',
  receiptLocation: '(Silver case)',
  url: 'https://en.wikipedia.org/wiki/Castlevania:_Circle_of_the_Moon',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'ffe1a56f-6a75-4c55-9627-a154bcc1fd8b',
  name: 'Classic NES Series: Bomberman',
  receiptLocation: '(Silver case)',
  url: 'https://en.wikipedia.org/wiki/List_of_Classic_NES_Series_games',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '1cb5aeb5-b57a-4f2a-ba41-14139b8df51b',
  name: 'Classic NES Series: Ice Climbers',
  receiptLocation: '(Silver case)',
  url: 'https://en.wikipedia.org/wiki/List_of_Classic_NES_Series_games',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '81b15ff1-0b7a-44db-a826-8926d56299ef',
  name: 'Crash Bandicoot: The Huge Adventure',
  receiptLocation: '(Silver case)',
  url: 'https://en.wikipedia.org/wiki/Crash_Bandicoot:_The_Huge_Adventure',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'afd2c69c-9591-41d4-a96d-b5d774374eb3',
  name: 'Crash Bandicoot 2: N-Tranced',
  receiptLocation: '(Silver case)',
  url: 'https://en.wikipedia.org/wiki/Crash_Bandicoot_2:_N-Tranced',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '4aba58bc-f251-44e0-a880-524f4fb0cd08',
  name: 'Crash & Spyro Superpack Volume 2: Crash Nitro Kart & Spyro 2: Season of Flame',
  receiptLocation: '',
  url: 'https://crashbandicoot.fandom.com/wiki/Crash_%26_Spyro_Super_Pack_Volume_2',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '72f3a32e-5913-4bef-b87a-5ab67340711a',
  name: 'Donkey Kong Country Advance',
  receiptLocation: '(Silver case)',
  url: 'https://en.wikipedia.org/wiki/Donkey_Kong_Country#Re-releases',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '161bd387-74ee-4d29-a178-4e3584a19972',
  name: 'Donkey Kong Country Advance 2: Diddy\'s Kong Quest',
  receiptLocation: '(Silver case)',
  url: 'https://en.wikipedia.org/wiki/Donkey_Kong_Country_2:_Diddy%27s_Kong_Quest#Sequels_and_re-releases',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '947db829-598a-44a3-a9e2-3ac12ae5f1db',
  name: 'Dragon Ball Z: The Legacy of Goku II',
  receiptLocation: '(Silver case)',
  url: 'https://en.wikipedia.org/wiki/Dragon_Ball_Z:_The_Legacy_of_Goku_(series)',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '93b74670-a474-40c7-854c-a2cf9d8efa45',
  name: 'Drill Dozer',
  receiptLocation: 'Harvest Moon: Save the Homeland',
  url: 'https://en.wikipedia.org/wiki/Drill_Dozer',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '5191edbb-5bf2-4899-9d01-66bfe9ff8ca7',
  name: 'Dr. Mario & Puzzle League',
  receiptLocation: '(Silver case)',
  url: 'https://www.mariowiki.com/Dr._Mario_%26_Puzzle_League',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '3ee63d7b-1778-4a33-9300-08e3ddcc96d8',
  name: 'Duke Nukem Advance',
  receiptLocation: 'Suikoden IV',
  url: 'https://en.wikipedia.org/wiki/Duke_Nukem_Advance',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '778b70c9-016c-4a8f-aa2c-70619b145b7c',
  name: 'Final Fantasy I & II: Dawn of Souls',
  receiptLocation: '(Silver case)',
  url: 'https://en.wikipedia.org/wiki/Final_Fantasy_(video_game)#Versions_and_re-releases',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '4a5915e3-18b6-4c42-a9b3-f7c89f767c31',
  name: 'Final Fantasy V Advance',
  receiptLocation: 'Ratchet & Clank: Up Your Arsenal',
  url: 'https://en.wikipedia.org/wiki/Final_Fantasy_V#Ports_and_remakes',
  price: 0,
  extras: [],
  played: true,
  completed: true,
  favourite: true,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'ae7fa842-deac-4759-98aa-4d9c049e045f',
  name: 'Final Fantasy Tactics Advance',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Final_Fantasy_Tactics_Advance',
  price: 0,
  extras: [],
  played: true,
  completed: true,
  favourite: true,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '5f88ff53-3f2b-42bb-87db-5f63d874ba46',
  name: 'Finding Nemo',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Finding_Nemo_(video_game)',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'c3fa5899-3161-4c8e-b693-cecaa5ca1173',
  name: 'Fire Emblem',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Fire_Emblem_(video_game)',
  price: 0,
  extras: [],
  played: true,
  completed: true,
  favourite: true,
  borrowedInFrom: 'Caelan',
  borrowedOutTo: '',
}, {
  id: '6ac062a7-ae0b-48e6-9f3a-80653fc41c95',
  name: 'Fire Emblem: The Sacred Stones',
  receiptLocation: '(Silver case)',
  url: 'https://en.wikipedia.org/wiki/Fire_Emblem:_The_Sacred_Stones',
  price: 0,
  extras: [],
  played: true,
  completed: true,
  favourite: true,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '7e7b033d-b998-452f-942d-d7edda7d373a',
  name: 'F-Zero: Maximum Velocity',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/F-Zero:_Maximum_Velocity',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'c88cb1d5-a2c9-40f1-a2bb-d11b874996a1',
  name: 'Golden Sun',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Golden_Sun',
  price: 0,
  extras: [],
  played: true,
  completed: true,
  favourite: true,
  borrowedInFrom: 'Max',
  borrowedOutTo: '',
}, {
  id: 'a1c38e93-643b-43ca-944d-051076ac3142',
  name: 'Golden Sun: The Lost Age',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Golden_Sun:_The_Lost_Age',
  price: 0,
  extras: [],
  played: true,
  completed: true,
  favourite: true,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'fe17d395-af87-4ee2-8f6c-fe64bb2658cb',
  name: 'Grand Theft Auto',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Grand_Theft_Auto_Advance',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '69df57a0-954e-4a7c-8253-fa887f32934d',
  name: 'Gunstar Super Heroes',
  receiptLocation: '(Toyratt)',
  url: 'https://en.wikipedia.org/wiki/Gunstar_Super_Heroes',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '9c6a0d15-ff91-436f-bc38-0c995bf4fa0c',
  name: 'Harvest Moon: Friends of Mineral Town',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Harvest_Moon:_Friends_of_Mineral_Town',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'c128f614-9dde-4e53-8ccc-3dd01cf92f99',
  name: 'Kirby & the Amazing Mirror',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Kirby_%26_the_Amazing_Mirror',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'd396eb08-745a-4ed5-9a9d-5ff3f5018303',
  name: 'Kirby: Nightmare in Dream Land',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Kirby%27s_Adventure#Rereleases',
  price: 0,
  extras: [],
  played: true,
  completed: true,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'c3f306de-8b90-4436-bfc1-b519a3fc460d',
  name: 'Lord of the Rings: Two Towers',
  receiptLocation: '(Silver case)',
  url: 'https://en.wikipedia.org/wiki/The_Lord_of_the_Rings:_The_Two_Towers_(video_game)',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'defba076-d348-4547-ade6-fac73ff9ded8',
  name: 'Lord of the Rings: Return of the King',
  receiptLocation: '(Silver case)',
  url: 'https://en.wikipedia.org/wiki/The_Lord_of_the_Rings:_The_Return_of_the_King_(video_game)',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'a424574a-90a4-447b-b5e8-79f46a8a5b31',
  name: 'Mario Kart Super Circuit',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Mario_Kart:_Super_Circuit',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'e254fbcf-93b1-47d0-ac80-495851a7214a',
  name: 'Mario & Luigi: Superstar Saga',
  receiptLocation: 'Paper Mario: The Thousand-Year Door',
  url: 'https://en.wikipedia.org/wiki/Mario_%26_Luigi:_Superstar_Saga',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '7c5ee2ee-55d8-4a2c-885c-46c98faa1619',
  name: 'Mario Party Advance',
  receiptLocation: '(Silver case)',
  url: 'https://en.wikipedia.org/wiki/Mario_Party_Advance',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '4ac14c92-8eea-485a-9cf3-4a46462fb137',
  name: 'Mario Tennis: Power Tour',
  receiptLocation: 'Paper Mario: The Thousand-Year Door',
  url: 'https://en.wikipedia.org/wiki/Mario_Tennis:_Power_Tour',
  price: 0,
  extras: [],
  played: true,
  completed: true,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'a8133ca0-66b8-42f4-9ea2-11e2ce71e979',
  name: 'Mega Man Battle Network',
  receiptLocation: 'Kingdom Hearts: Chain of Memories',
  url: 'https://en.wikipedia.org/wiki/Mega_Man_Battle_Network_(video_game)',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'f6889944-2359-4a2f-bb2e-4ae87b515f0d',
  name: 'Mega Man Battle Network 2',
  receiptLocation: '(Silver case)',
  url: 'https://en.wikipedia.org/wiki/Mega_Man_Battle_Network_2',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '4fd14da5-a735-4b30-b1d8-af9804ad1817',
  name: 'Mega Man Battle Network 3: Blue',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Mega_Man_Battle_Network_3',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '9bde46a4-6dd7-46b5-a853-9c31a7c505b6',
  name: 'Mega Man Battle Network 4: Blue Moon',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Mega_Man_Battle_Network_4',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'f556de06-ff52-4d4b-86ee-80d814537420',
  name: 'Mega Man Battle Network 5: Team Protoman',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Mega_Man_Battle_Network_5',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: 'Max',
  borrowedOutTo: '',
}, {
  id: '291ae49f-6ccf-46c2-936d-1c27311a2a2a',
  name: 'Mega Man Battle Network 6: Cybeast Falzar',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Mega_Man_Battle_Network_6',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '494c0777-436a-45ca-a614-4a4969243765',
  name: 'Mega Man & Bass',
  receiptLocation: 'Final Fantasy X',
  url: 'https://en.wikipedia.org/wiki/Mega_Man_%26_Bass',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '4a9af5fd-061e-418c-9d13-ce6f1d0a532c',
  name: 'Mega Man Zero 2',
  receiptLocation: 'Pikmin',
  url: 'https://en.wikipedia.org/wiki/Mega_Man_Zero_2',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '62fe7c26-35f2-458e-a05a-f328800f9bfe',
  name: 'Mega Man Zero 4',
  receiptLocation: 'Pikmin',
  url: 'https://en.wikipedia.org/wiki/Mega_Man_Zero_4',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'abcf5bd7-a505-486f-be13-e6967c0b84e5',
  name: 'Metal Slug Advance',
  receiptLocation: 'Paper Mario: The Thousand-Year Door',
  url: 'https://en.wikipedia.org/wiki/Metal_Slug_Advance',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'd7478d9f-9304-45c8-8e29-20716a17b461',
  name: 'Metroid Fusion',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Metroid_Fusion',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: 'Max',
  borrowedOutTo: '',
}, {
  id: '9dfdbd54-d5e2-42e4-a85a-c7a0fbaf5fbd',
  name: 'Metroid: Zero Mission',
  receiptLocation: '(Silver case)',
  url: 'https://en.wikipedia.org/wiki/Metroid:_Zero_Mission',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '1dbfd40e-6c4d-45ce-9682-281409063eb5',
  name: 'Monster Rancher Advance',
  receiptLocation: 'Little Big Planet',
  url: 'https://en.wikipedia.org/wiki/Monster_Rancher_Advance',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '6640e7b3-b6f9-4f4d-a3a6-0e0badd16c5f',
  name: 'Nicktoons: Freeze Frame Frenzy',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Nicktoons:_Freeze_Frame_Frenzy',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '3ff9f8c1-0503-4c5f-ad2b-ef5406c8375b',
  name: 'Onimusha Tactics',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Onimusha_Tactics',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '61370d94-6ac3-410e-b51f-76077cc18d57',
  name: 'Phantasy Star Collection',
  receiptLocation: 'Suikoden IV',
  url: 'https://en.wikipedia.org/wiki/Phantasy_Star_Collection',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '7cd31449-602c-4990-8a76-10c9fe39fefd',
  name: 'Pokemon Sapphire',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Pok%C3%A9mon_Ruby_and_Sapphire',
  price: 0,
  extras: [],
  played: true,
  completed: true,
  favourite: true,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '567c1a65-fb5c-4858-8045-b028ff585793',
  name: 'Pokemon Ruby',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Pok%C3%A9mon_Ruby_and_Sapphire',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: 'Jack',
  borrowedOutTo: '',
}, {
  id: '0383d581-8c0b-4b20-931b-6e2138c58b55',
  name: 'Pokemon LeafGreen',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Pok%C3%A9mon_FireRed_and_LeafGreen',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: 'Max',
  borrowedOutTo: '',
}, {
  id: '91da710a-12f5-4bfd-b956-eb6168a85fad',
  name: 'Pokemon FireRed',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Pok%C3%A9mon_FireRed_and_LeafGreen',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: 'Max',
  borrowedOutTo: '',
}, {
  id: 'bccba9c3-efe8-4fbe-a739-e6a5a34c7d81',
  name: 'Pokemon Pinball: Ruby and Sapphire',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Pok%C3%A9mon_Pinball:_Ruby_%26_Sapphir',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '2b6fd768-8068-46fd-8d6b-78ff6defee63',
  name: 'The Sims Bustin\' Out',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/The_Sims_Bustin%27_Out',
  price: 0,
  extras: [],
  played: true,
  completed: true,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'dc760e55-2f4d-4673-8711-cb187db9ded6',
  name: 'The Sims 2',
  receiptLocation: '(Silver case)',
  url: 'https://en.wikipedia.org/wiki/The_Sims_2#Game_Boy_Advance_version',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'c06bfbd8-b295-42b1-b241-cd532a807f75',
  name: 'Sonic Advance 2',
  receiptLocation: 'Paper Mario: The Thousand-Year Door',
  url: 'https://en.wikipedia.org/wiki/Sonic_Advance_2',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '09e5d91a-6947-40d0-98a1-7f8107f21e4d',
  name: 'Sonic Advance 3',
  receiptLocation: '(Silver case)',
  url: 'https://en.wikipedia.org/wiki/Sonic_Advance_3',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'd6eafef9-5d81-4474-ae9c-c8f14df34a68',
  name: 'Spiderman 2',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Spider-Man_2_(video_game)',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'd874a3a3-02cf-4167-adb3-91189180a074',
  name: 'SpongeBob SquarePants: Battle for Bikini Bottom',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/SpongeBob_SquarePants:_Battle_for_Bikini_Bottom',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'b24e1c3d-5d69-4c96-9ca2-71ba98760ee8',
  name: 'SpongeBob SquarePants: Supersponge/Revenge of the Flying Dutchman',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/SpongeBob_SquarePants:_Revenge_of_the_Flying_Dutchman',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'fed324f4-ae8b-4882-b077-988b7c456180',
  name: 'Spyro Orange: The Cortex Conspiracy',
  receiptLocation: 'Harvest Moon: A Wonderful Life',
  url: 'https://en.wikipedia.org/wiki/Crash_Bandicoot_Purple:_Ripto%27s_Rampage_and_Spyro_Orange:_The_Cortex_Conspiracy',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'a4b5a484-14df-4906-8126-fd3affa6917e',
  name: 'Super Mario Advance: Super Mario Bros. 2 ',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Super_Mario_Bros._2#Super_Mario_Advance',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '7ac7cb85-a772-4c75-8dde-a3d24a2412cc',
  name: 'Super Mario Advance 2: Super Mario World',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Super_Mario_World#Releases',
  price: 0,
  extras: [],
  played: true,
  completed: true,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'f3dcd672-6d3c-4ea9-a8bb-2ca4fb5e9bc6',
  name: 'Super Mario Advance 3: Yoshi\'s Island ',
  receiptLocation: '(Silver case)',
  url: 'https://en.wikipedia.org/wiki/Yoshi%27s_Island#Development_and_rerelease',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '8e06b5ca-adb4-47d5-9c1f-dac111800182',
  name: 'Super Mario Advance 4: Super Mario Bros 3 ',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Super_Mario_Advance_4:_Super_Mario_Bros._3#Development_and_release',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'a44a9efa-6663-40c0-9844-51f0d995018d',
  name: 'Summon Night: Swordcraft Story',
  receiptLocation: 'Sonic Adventure 2',
  url: 'https://en.wikipedia.org/wiki/Summon_Night:_Swordcraft_Story',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'b70f971b-0d8e-4a41-9e53-160a2075765d',
  name: 'Summon Night: Swordcraft Story 2',
  receiptLocation: 'Sonic Adventure 2',
  url: 'https://en.wikipedia.org/wiki/Summon_Night:_Swordcraft_Story_2',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '948bfe29-3a4e-46b8-8cdb-bebc0c1d1c59',
  name: 'Sword of Mana',
  receiptLocation: '(Silver case)',
  url: 'https://en.wikipedia.org/wiki/Sword_of_Mana',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '3c745866-674e-45c0-bb10-031ce8f0bdb6',
  name: 'Tactics Ogre: The Knight of Lodis',
  receiptLocation: 'Worms Armageddon',
  url: 'https://en.wikipedia.org/wiki/Tactics_Ogre:_The_Knight_of_Lodis',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '195303fb-0c50-489c-8384-b3f5a272098c',
  name: 'Teenage Mutant Ninja Turtles',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Teenage_Mutant_Ninja_Turtles_(Game_Boy_Advance)',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '45c11157-77b9-4ad3-a4bb-ff56bd7b6c98',
  name: 'The Legend of Zelda: A Link To The Past and Four Swords',
  receiptLocation: '(Silver case)',
  url: 'https://en.wikipedia.org/wiki/The_Legend_of_Zelda:_A_Link_to_the_Past_and_Four_Swords',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'b8b70160-525d-4147-beb5-8855cf663bdd',
  name: 'The Legend of Zelda: The Minish Cap',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/The_Legend_of_Zelda:_The_Minish_Cap',
  price: 0,
  extras: [],
  played: true,
  completed: true,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: 'Jack?',
}, {
  id: '01713f0c-bf4a-4b23-930e-2abd6c75615a',
  name: 'Tony Hawk\'s Pro Skater 4',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Tony_Hawk%27s_Pro_Skater_4',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'a886fdcf-fb27-4c75-b4f1-5fd5cd544496',
  name: 'Wario Land 4',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Wario_Land_4',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '899bb884-8ead-49f5-89d8-4c8af28c8848',
  name: 'Yggdra Union: We\'ll Never Fight Alone',
  receiptLocation: 'Kingdom Hearts Birth by Sleep',
  url: 'https://en.wikipedia.org/wiki/Yggdra_Union',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '36de2c41-1b78-436e-a12a-4259c930da0d',
  name: 'Yu-Gi-Oh! The Sacred Cards',
  receiptLocation: 'Dragon Ball Z Budokai 2',
  url: 'https://en.wikipedia.org/wiki/Yu-Gi-Oh!_The_Sacred_Cards',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '4344511e-5380-4a0a-94e9-4295032e249e',
  name: 'Yu-Gi-Oh! World Champion Tournament 2004',
  receiptLocation: 'Naruto: Clash of Ninja',
  url: 'https://en.wikipedia.org/wiki/Yu-Gi-Oh!_World_Championship_Tournament_2004',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}]

export default {
  id: '286e78dd-936e-4d5b-89ce-086277b0d7ce',
  name: 'Game Boy Advance',
  systems,
  cables,
  accessories,
  controllers,
  games,
}
