const systems = []

const cables = []

const accessories = []

const controllers = []

const games = [{
  id: 'c417564a-5793-4e01-bec8-26a072609f47',
  name: 'Age of Mythology',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Age_of_Mythology',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '969f4e42-ef2c-4087-8dc9-509554084d30',
  name: 'From Dust',
  receiptLocation: '(Steam)',
  url: 'https://en.wikipedia.org/wiki/From_Dust',
  price: 0,
  tags: [],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'a1502363-93b8-4b18-9f4f-6ee1fd4855c2',
  name: 'Minecraft',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Minecraft',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '0e35a53d-3c1e-4201-b008-46441d8f4987',
  name: 'Portal',
  receiptLocation: '(Steam)',
  url: 'https://en.wikipedia.org/wiki/Portal_(video_game)',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: true,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '39ef129c-798a-4e3f-b5e7-19fe4fab493e',
  name: 'Portal 2',
  receiptLocation: '(Steam)',
  url: 'https://en.wikipedia.org/wiki/Portal_2',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '1257480e-e898-4f72-a1e8-69ce2f56ead9',
  name: 'Rollercoaster Tycoon',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/RollerCoaster_Tycoon_(video_game)',
  price: 0,
  tags: ['rct'],
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '5af8abdd-3817-470f-987d-567c9717690e',
  name: 'Rollercoaster Tycoon 2',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/RollerCoaster_Tycoon_2',
  price: 0,
  tags: ['rct2'],
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '654e568f-2ad7-4849-a1a2-fd758795a149',
  name: 'The Sims 2',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/The_Sims_2',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '91b9129e-35a1-478a-9a2c-32070923f6a2',
  name: 'The Sims 3',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/The_Sims_3',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '1651554f-0d3f-4100-be92-93aa431ef255',
  name: 'The Sims 4',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/The_Sims_4',
  price: 0,
  tags: [],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'cc31d1b5-0cc6-4ae6-a966-db27b9b2a482',
  name: 'Spore',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Spore_(2008_video_game)',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: true,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'd4b7ad94-e635-48fd-8ec5-b40f24733816',
  name: 'Terraria',
  receiptLocation: '(Steam)',
  url: 'https://en.wikipedia.org/wiki/Terraria',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}]

export default {
  id: '9dae8f3f-1de4-407e-9c68-b54dd7950199',
  name: 'PC',
  index: 16,
  systems,
  cables,
  accessories,
  controllers,
  games,
}
