const systems = [{
  id: 'ac80ef97-92b0-497f-b569-951d6f875961',
  color: 'Grey',
  description: 'PS one (smaller redesign)',
  borrowedInFrom: '',
  borrowedOutTo: '',
}]

const cables = ['Power', 'AV']

const accessories = ['Controller connector']

const controllers = ['Grey x2']

const games = [{
  id: '39b1ffb1-c76f-4948-aec4-60bca24680e7',
  name: 'Alundra',
  receiptLocation: '(Mac Game Guy)',
  url: 'https://en.wikipedia.org/wiki/Alundra',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'ec997696-8105-462e-b392-925f5a213814',
  name: 'Alundra 2: A New Legend Begins',
  receiptLocation: '(Mac Game Guy)',
  url: 'https://en.wikipedia.org/wiki/Alundra_2',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '4d4aab02-4c38-45d7-a1f0-ce1c30d66fb1',
  name: 'Ape Escape',
  receiptLocation: 'Pikmin',
  url: 'https://en.wikipedia.org/wiki/Ape_Escape_(video_game)',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '213136e2-8a61-43a7-a8b8-3359e3879c58',
  name: 'Breath of Fire IV',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Breath_of_Fire_IV',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '0cc0b135-b106-4b4f-a7f0-5878b756d80e',
  name: 'Chrono Cross',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Chrono_Cross',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '8d7033bb-9867-4f76-bfa9-124baf1079e0',
  name: 'Crash Team Racing',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Crash_Team_Racing',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '9dac5fb4-852d-4a70-9741-4cdcb77f4efe',
  name: 'Dragon Warrior VII',
  receiptLocation: 'Skies of Arcadia',
  url: 'https://en.wikipedia.org/wiki/Dragon_Quest_VII',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'bd2d0c61-4bfd-42f8-968d-cc53324724fe',
  name: 'Final Fantasy Tactics',
  receiptLocation: 'Xenogears',
  url: 'https://en.wikipedia.org/wiki/Final_Fantasy_Tactics',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '845a252a-dc21-4a3f-a7b0-1dc8e7c9f7df',
  name: 'Final Fantasy VII',
  receiptLocation: 'Final Fantasy X',
  url: 'https://en.wikipedia.org/wiki/Final_Fantasy_VII',
  price: 0,
  extras: ['Guidebook'],
  played: true,
  completed: true,
  favourite: true,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '6a264d78-5e1b-4982-9446-0ac085802977',
  name: 'Final Fantasy VIII',
  receiptLocation: 'Metal Gear Solid 2: Sons of Liberty',
  url: 'https://en.wikipedia.org/wiki/Final_Fantasy_VIII',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '790e3219-bf25-4e31-b958-e40253ac93b9',
  name: 'Final Fantasy IX',
  receiptLocation: 'Ys: The Ark of Napishtim',
  url: 'https://en.wikipedia.org/wiki/Final_Fantasy_IX',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'fa6fbd80-5c2b-4c53-ba97-1390b6bddc0a',
  name: 'Gran Turismo 2',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Gran_Turismo_2',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'bac9724f-ea7f-4c3f-a581-477475e216cc',
  name: 'Grandia',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Grandia_(video_game)',
  price: 0,
  extras: [],
  played: true,
  completed: true,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'b8ca7f16-a702-4f1f-8798-16d45176c219',
  name: 'Harvest Moon: Back To Nature',
  receiptLocation: 'Phantom Brave',
  url: 'https://en.wikipedia.org/wiki/Harvest_Moon:_Back_to_Nature',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '4c05ef20-798d-4dfe-af52-292dd166410c',
  name: 'Jeremy McGrath Supercross \'98',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Jeremy_McGrath_Supercross_98',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'aa98dac7-874f-4360-8069-3a8271a27063',
  name: 'The Legend of Dragoon',
  receiptLocation: 'Final Fantasy X-2',
  url: 'https://en.wikipedia.org/wiki/The_Legend_of_Dragoon',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '0034fdcd-6525-4cfc-b673-e404537e77e1',
  name: 'Legend of Legaia',
  receiptLocation: 'Grandia',
  url: 'https://en.wikipedia.org/wiki/Legend_of_Legaia',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '491b9312-2e73-4ea0-b21e-b889451ced21',
  name: 'Legend of Mana',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Legend_of_Mana',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'a892cbe9-8a5e-4d18-b8d7-d2aa60fedc14',
  name: 'Mega Man 8',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Mega_Man_8',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '4029db4a-a3fb-42b9-b56c-7fd381f609e8',
  name: 'Metal Gear Solid',
  receiptLocation: 'Metal Gear Solid 2: Sons of Liberty',
  url: 'https://en.wikipedia.org/wiki/Metal_Gear_Solid',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'e41b935d-866f-4764-82c2-862f767b5b05',
  name: 'Monster Ranchers',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Monster_Rancher_(video_game)',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '1525a7f5-609b-4f98-852b-45c49d67d9cb',
  name: 'Moto Racer',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Moto_Racer',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '96ccaecc-a770-4f14-99f5-0b7474816f63',
  name: 'Parasite Eve',
  receiptLocation: 'Xenogears',
  url: 'https://en.wikipedia.org/wiki/Parasite_Eve_(video_game)',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'fe2f1a84-acbf-41b9-906e-ff7b73e55fe5',
  name: 'Parasite Eve II',
  receiptLocation: 'Xenogears',
  url: 'https://en.wikipedia.org/wiki/Parasite_Eve_II',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '64411a0a-84e1-4f44-b199-deef9519e65e',
  name: 'Rayman',
  receiptLocation: 'Pikmin',
  url: 'https://en.wikipedia.org/wiki/Rayman_(video_game)',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'ed4031fd-e815-47de-b82d-25d5ab81ad23',
  name: 'SaGa Frontier',
  receiptLocation: 'Xenogears',
  url: 'https://en.wikipedia.org/wiki/SaGa_Frontier',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '1ddd40e5-a6b1-444e-86bc-ab904de5510e',
  name: 'Soviet Strike',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Soviet_Strike',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'b205f5e7-b8c6-46e8-accb-64085cbb61a5',
  name: 'Spyro 2: Ripto\'s Rage!',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Spyro_2:_Ripto%27s_Rage!',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '2460269a-93d5-4cfe-879a-ba15ef8be5ff',
  name: 'Spyro: Year of the Dragon',
  receiptLocation: 'Dragon Ball Z Budokai 2',
  url: 'https://en.wikipedia.org/wiki/Spyro:_Year_of_the_Dragon',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'c12a87f7-1444-4864-8d3d-70f0325f407f',
  name: 'Star Ocean: The Second Story',
  receiptLocation: '(Toyratt)',
  url: 'https://en.wikipedia.org/wiki/Star_Ocean:_The_Second_Story',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'ea459b8f-b484-46ed-8420-59c7781d68f9',
  name: 'Suikoden I',
  receiptLocation: 'Suikoden IV',
  url: 'https://en.wikipedia.org/wiki/Suikoden_(video_game)',
  price: 0,
  extras: [],
  played: true,
  completed: true,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'b183c166-9a4a-4336-adcb-4abb8000727f',
  name: 'Suikoden II',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Suikoden_II',
  price: 0,
  extras: [],
  played: true,
  completed: true,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'c04e0f9b-e76c-4064-9c8b-8c528ef1c755',
  name: 'Tales of Destiny',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Tales_of_Destiny',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '7806094b-5d13-42c1-ac2e-1b1b9de28dc2',
  name: 'Tales of Eternia (Destiny II)',
  receiptLocation: 'Skies of Arcadia',
  url: 'https://en.wikipedia.org/wiki/Tales_of_Eternia',
  price: 0,
  extras: [],
  played: true,
  completed: true,
  favourite: true,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '6a8e8f92-bd11-4a10-9587-4652e3f7d154',
  name: 'Tekken 3',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Tekken_3',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '019f5194-e054-4fb9-984b-4628e849fc5c',
  name: 'Threads of Fate',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Threads_of_Fate',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'd0c3863c-b6f0-4ae7-9e5e-670e6beda638',
  name: 'Tomb Raider',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Tomb_Raider_(1996_video_game)',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '18a15979-68c5-4c57-937a-594683077258',
  name: 'Twisted Metal III',
  receiptLocation: 'ZHP',
  url: 'https://en.wikipedia.org/wiki/Twisted_Metal_III',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '8aa70eda-36ac-4972-b4f4-2eb0552b0221',
  name: 'Vagrant Story',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Vagrant_Story',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'eb97e9a7-9ac8-461a-8052-716fb480f360',
  name: 'Wild Arms',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Wild_Arms_(video_game)',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '3850a4b0-fa5d-49a7-8521-725aabc17ccd',
  name: 'Wild Arms 2',
  receiptLocation: '(Toyratt)',
  url: 'https://en.wikipedia.org/wiki/Wild_Arms_2',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '4702125c-7638-4b6c-979b-739f1140b7ae',
  name: 'Xenogears',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Xenogears',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}]

export default {
  id: '6117732e-9cef-4d24-b974-235ba823a758',
  name: 'PS1 (PlayStation)',
  systems,
  cables,
  accessories,
  controllers,
  games,
}
