const systems = [{
  id: '526d4a3b-d57f-4389-b4c1-b679c3ae194e',
  color: 'Black',
  description: 'Slimline',
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '8df8761d-9c7e-438d-ad3c-763a4cc19afc',
  color: 'Black',
  description: 'Slimline',
  borrowedInFrom: '',
  borrowedOutTo: '',
}]

const cables = ['Power', 'AV']

const accessories = ['Controller connector']

const controllers = ['Black x2', 'Blue']

const games = [{
  id: '1b977806-c074-477d-89f9-703ded40ff45',
  name: '007 From Russia with Love',
  receiptLocation: 'Bioshock',
  url: 'https://en.wikipedia.org/wiki/James_Bond_007:_From_Russia_with_Love',
  price: 0,
  tags: ['james bond'],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'da736234-9d84-4382-b7e4-c5eb61d12a05',
  name: 'Dance Dance Revolution Extreme 2',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Dance_Dance_Revolution_Extreme_2',
  price: 0,
  tags: ['ddr'],
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'f5141ffe-2c34-4c03-9e03-01e3020ff117',
  name: 'Dark Cloud',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Dark_Cloud',
  price: 0,
  tags: [],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '04a5f1df-44f0-4df4-a144-5d1ecadd780d',
  name: 'Dark Cloud 2',
  receiptLocation: 'Phantom Brave',
  url: 'https://en.wikipedia.org/wiki/Dark_Chronicle',
  price: 0,
  tags: [],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '5bcf4859-fac8-4d22-b710-15e597cb7a7d',
  name: 'Dawn of Mana',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Dawn_of_Mana',
  price: 0,
  tags: [],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '577e529d-fa8d-461f-b021-740a7945a7af',
  name: 'Devil May Cry',
  receiptLocation: 'Disgaea 2: Cursed Memories',
  url: 'https://en.wikipedia.org/wiki/Devil_May_Cry_(video_game)',
  price: 0,
  tags: ['dmc'],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '7fbb919c-7133-46f0-be2b-10651d260001',
  name: 'Devil May Cry 2',
  receiptLocation: 'Disgaea 2: Cursed Memories',
  url: 'https://en.wikipedia.org/wiki/Devil_May_Cry_2',
  price: 0,
  tags: ['dmc2'],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '77795e1f-6c0a-45a5-b288-c47bf937c0f0',
  name: 'Devil May Cry 3: Dante\'s Awakening',
  receiptLocation: 'Disgaea 2: Cursed Memories',
  url: 'https://en.wikipedia.org/wiki/Devil_May_Cry_3:_Dante%27s_Awakening',
  price: 0,
  tags: ['dmc3'],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'd40891e4-fa10-45b4-b0de-a663101233b8',
  name: 'Dirge of Cerberus: Final Fantasy VII',
  receiptLocation: 'Kingdom Hearts: Chain of Memories',
  url: 'https://en.wikipedia.org/wiki/Dirge_of_Cerberus:_Final_Fantasy_VII',
  price: 0,
  tags: ['ffvii', 'ff7'],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '7097533b-a0ed-4a36-a0c0-92cd0744d576',
  name: 'Disgaea: Hour of Darkness',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Disgaea:_Hour_of_Darkness',
  price: 0,
  tags: [],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '2080673e-996e-4348-bf66-5c32edd8caa2',
  name: 'Disgaea 2: Cursed Memories',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Disgaea_2',
  price: 0,
  tags: [],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'd40b6b7e-78ff-4175-b752-ebf7a964c40e',
  name: 'Dragon Ball Z Budokai',
  receiptLocation: 'Bioshock',
  url: 'https://en.wikipedia.org/wiki/Dragon_Ball_Z:_Budokai#Budokai',
  price: 0,
  tags: ['dbz'],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '2ffe9215-185a-49db-a9da-f238455f50b1',
  name: 'Dragon Ball Z Budokai 2',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Dragon_Ball_Z:_Budokai#Budokai_2',
  price: 0,
  tags: ['dbz'],
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '1a8f12ec-a72a-45db-9448-9059b501aaaa',
  name: 'Dragon Ball Z Budokai Tenkaichi',
  receiptLocation: 'Dragon Ball Z Budokai 2',
  url: 'https://en.wikipedia.org/wiki/Dragon_Ball_Z:_Budokai_Tenkaichi#Dragon_Ball_Z:_Budokai_Tenkaichi',
  price: 0,
  tags: ['dbz'],
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '4936a256-9fef-40fc-9cb8-5e91ff340c01',
  name: 'Dragon Ball Z Budokai Tenkaichi 2',
  receiptLocation: 'Dragon Ball Z Budokai 2',
  url: 'https://en.wikipedia.org/wiki/Dragon_Ball_Z:_Budokai_Tenkaichi#Dragon_Ball_Z:_Budokai_Tenkaichi_2',
  price: 0,
  tags: ['dbz'],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'ce63634b-1904-49d6-ac5e-102ee22f965e',
  name: 'Dragon Quest VIII: Journey of the Cursed King',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Dragon_Quest_VIII',
  price: 0,
  tags: ['dq8', 'dw8'],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '37f427f2-f4d1-41bd-96b5-ea82f563777e',
  name: 'Final Fantasy X',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Final_Fantasy_X',
  price: 0,
  tags: ['ffx', 'ff10'],
  extras: [],
  played: true,
  completed: true,
  favourite: true,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '33a2c210-96de-4126-a3a0-e673831c429d',
  name: 'Final Fantasy X-2',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Final_Fantasy_X-2',
  price: 0,
  tags: ['ffx-2', 'ff10-2'],
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '8d5e53c9-87bd-413b-921a-3de9f5e3fafc',
  name: 'Final Fantasy XI Online',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Final_Fantasy_XI',
  price: 9,
  tags: ['ffxi', 'ff11'],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'cd33aad8-cc14-422f-a46d-a3eee340a2e7',
  name: 'Final Fantasy XII',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Final_Fantasy_XII',
  price: 0,
  tags: ['ffxii', 'ff12'],
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '216ca194-504e-4db0-8afe-1afb09872f49',
  name: 'God of War',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/God_of_War_(2005_video_game)',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: true,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'e3e3a906-5e1b-41c0-be5b-4d593eea1d53',
  name: 'Grand Theft Auto III',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Grand_Theft_Auto_III',
  price: 0,
  tags: ['gta3'],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '3aa15d5a-082e-4b1f-bdef-48fe2176ce10',
  name: 'Grand Theft Auto: Vice City',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Grand_Theft_Auto:_Vice_City',
  price: 0,
  tags: ['gta', 'vc'],
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'ebf54239-01bc-4701-8799-b5f2d414fbe6',
  name: 'Grand Theft Auto: San Andreas',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Grand_Theft_Auto:_San_Andreas',
  price: 0,
  tags: ['gta'],
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'c1b0d22e-870d-4826-9a9e-4053f85098cf',
  name: 'Grandia II',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Grandia_II#Ports',
  price: 0,
  tags: ['2'],
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '2c12516a-6d73-4876-a9a7-18775a5eebfc',
  name: 'Grandia III',
  receiptLocation: 'Vagrant Story',
  url: 'https://en.wikipedia.org/wiki/Grandia_III',
  price: 0,
  tags: ['3'],
  extras: [],
  played: true,
  completed: true,
  favourite: true,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'afc3a87f-5868-4f9c-95b1-83caa85ca179',
  name: 'Grandia Xtreme',
  receiptLocation: 'Phantom Brave',
  url: 'https://en.wikipedia.org/wiki/Grandia_Xtreme',
  price: 0,
  tags: [],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '10984120-3649-4413-abba-06761fe30ec2',
  name: 'Growlanser Generaions',
  receiptLocation: '(Mac Game Guy)',
  url: 'https://en.wikipedia.org/wiki/Growlanser_Generations',
  price: 0,
  tags: [],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '145d7e1e-1ba7-4598-a43f-edef2cde5adb',
  name: 'Harvest Moon: Save the Homeland',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Harvest_Moon:_Save_the_Homeland',
  price: 0,
  tags: ['hm'],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '88f0b720-d133-4d3d-a7dd-362bc26fe30e',
  name: 'Ico',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Ico',
  price: 0,
  tags: [],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '0edd84c1-bd3f-4293-ac8e-51d8932c5110',
  name: 'Indigo Prophecy',
  receiptLocation: 'Worms Armageddon',
  url: 'https://en.wikipedia.org/wiki/Fahrenheit_(2005_video_game)',
  price: 0,
  tags: ['fahrenheit'],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '522b69b1-184a-4da5-910f-76d543266d63',
  name: 'Kingdom Hearts',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Kingdom_Hearts_(video_game)',
  price: 0,
  tags: ['kh'],
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'eac6f136-72ce-4ba2-b862-72c3d512e11d',
  name: 'Kingdom Hearts II',
  receiptLocation: 'Final Fantasy X-2',
  url: 'https://en.wikipedia.org/wiki/Kingdom_Hearts_II',
  price: 0,
  tags: ['kh2'],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'bc40e554-1c96-4662-b05b-f16db12c8457',
  name: 'Kingdom Hearts Re: Chain of Memories',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Kingdom_Hearts:_Chain_of_Memories#Kingdom_Hearts_Re:Chain_of_Memories',
  price: 0,
  tags: ['kh', 'com'],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '95181acb-8b7b-4c4e-bd63-4355010475bd',
  name: 'La Pucelle: Tactics',
  receiptLocation: 'Tales of Legendia',
  url: 'https://en.wikipedia.org/wiki/La_Pucelle:_Tactics',
  price: 0,
  tags: [],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'b06be297-0edd-4f32-b6ad-d88db3ee5230',
  name: 'Legaia 2: Duel Saga',
  receiptLocation: '(Mac Game Guy)',
  url: 'https://en.wikipedia.org/wiki/Legaia_2:_Duel_Saga',
  price: 0,
  tags: [],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'ce4c2504-7fc1-4b73-a908-cf72c34f2a1b',
  name: 'Marvel Nemesis: Rise of the Imperfects',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Marvel_Nemesis:_Rise_of_the_Imperfects',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '6bad218d-9fbc-4928-8e1a-2336e778f31f',
  name: 'Medal of Honor: European Assault',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Medal_of_Honor:_European_Assault',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '3192c6f8-6a74-4219-982c-968f4c956822',
  name: 'Mega Man X7',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Mega_Man_X7',
  price: 0,
  tags: [],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '5088193f-d820-4afb-9f41-dc7381e20b2e',
  name: 'Mega Man X: Command Mission',
  receiptLocation: 'Metal Gear Solid 2: Sons of Liberty',
  url: 'https://en.wikipedia.org/wiki/Mega_Man_X:_Command_Mission',
  price: 0,
  tags: [],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '6906dada-fa85-4689-a7aa-9444701aba23',
  name: 'Metal Gear Solid 2: Sons of Liberty',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Metal_Gear_Solid_2:_Sons_of_Liberty',
  price: 0,
  tags: ['mgs2'],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '8f4706cd-7b91-4c81-9e4a-c4cd464ae499',
  name: 'Metal Gear Solid 3: Snake Eater',
  receiptLocation: 'Metal Gear Solid 2: Sons of Liberty',
  url: 'https://en.wikipedia.org/wiki/Metal_Gear_Solid_3:_Snake_Eater',
  price: 0,
  tags: ['mgs3'],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '61c6d860-40a3-4854-9683-4f2fe9804403',
  name: 'Midnight Club 3: Dub Edition',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Midnight_Club_3:_Dub_Edition',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '63a8602a-cbd6-49f0-84c5-e2363dfa5c54',
  name: 'Nobunaga\'s Ambition: Rise to Power',
  receiptLocation: 'Disgaea: Hour of Darkness',
  url: 'https://en.wikipedia.org/wiki/Nobunaga%27s_Ambition',
  price: 0,
  tags: [],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '2766af94-3d75-40ea-a8eb-814cfa232ee0',
  name: 'Nobunaga\'s Ambition: Iron Triangle',
  receiptLocation: 'Disgaea: Hour of Darkness',
  url: 'https://en.wikipedia.org/wiki/Nobunaga%27s_Ambition',
  price: 0,
  tags: [],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '745d164e-c37a-418e-9ae0-ef0433e98703',
  name: 'Odin Sphere',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Odin_Sphere',
  price: 0,
  tags: [],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'b246fbba-5640-44a6-a744-1dd1f4addbc5',
  name: 'Onimusha: Warlords',
  receiptLocation: 'Disgaea: Hour of Darkness',
  url: 'https://en.wikipedia.org/wiki/Onimusha:_Warlords',
  price: 0,
  tags: [],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '69788bff-205b-4473-9618-df84c98fe5f3',
  name: 'Onimusha 2: Samurai\'s Destiny',
  receiptLocation: 'Disgaea: Hour of Darkness',
  url: 'https://en.wikipedia.org/wiki/Onimusha_2:_Samurai%27s_Destiny',
  price: 0,
  tags: [],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'cb49090d-d49b-4987-8860-a757d852e11a',
  name: 'Onimusha 3: Demon Siege',
  receiptLocation: 'Disgaea: Hour of Darkness',
  url: 'https://en.wikipedia.org/wiki/Onimusha_3:_Demon_Siege',
  price: 0,
  tags: [],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '99d897d9-c883-44ba-83c7-a74e99c544f9',
  name: 'Onimusha Blade Warriors',
  receiptLocation: 'ZHP',
  url: 'https://en.wikipedia.org/wiki/Onimusha_Blade_Warriors',
  price: 0,
  tags: [],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '4fb1544a-3f08-42e1-b7d9-39f55ae40ba0',
  name: 'Persona 3 FES',
  receiptLocation: '(Mac Game Guy)',
  url: 'https://en.wikipedia.org/wiki/Persona_3',
  price: 0,
  tags: [],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '507a7c2f-f72b-4dab-bbdb-0e8138a23d83',
  name: 'Phantasy Star Universe',
  receiptLocation: '(Toyratt)',
  url: 'https://en.wikipedia.org/wiki/Phantasy_Star_Universe',
  price: 0,
  tags: [],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '53ee7ef6-2eda-4ac9-8f76-580690877b16',
  name: 'Phantom Brave',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Phantom_Brave',
  price: 0,
  tags: [],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '0e0f5b3c-212a-46e4-bf7d-c692b6c3ebf6',
  name: 'Prince of Persia: The Sands of Time',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Prince_of_Persia:_The_Sands_of_Time',
  price: 0,
  tags: [],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '33e2d23c-1e64-4a9b-86cc-572df9ae1c97',
  name: 'Prince of Persia: Warrior Within',
  receiptLocation: 'Prince of Persia: The Sands of Time',
  url: 'https://en.wikipedia.org/wiki/Prince_of_Persia:_Warrior_Within',
  price: 0,
  tags: [],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '4ea5ade4-d683-43db-b98b-19c298f5abc9',
  name: 'Radiata Stories',
  receiptLocation: 'Suikoden IV',
  url: 'https://en.wikipedia.org/wiki/Radiata_Stories',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'd7b5ddb9-76ec-485b-98c8-133030666723',
  name: 'Ratchet & Clank',
  receiptLocation: 'Dragon Ball Z Budokai 2',
  url: 'https://en.wikipedia.org/wiki/Ratchet_%26_Clank_(2002_video_game)',
  price: 0,
  tags: [],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '38cbe464-153a-440c-871f-30d0c757c678',
  name: 'Ratchet & Clank 2: Going Commando',
  receiptLocation: 'Naruto: Clash of Ninja',
  url: 'https://en.wikipedia.org/wiki/Ratchet_%26_Clank:_Going_Commando',
  price: 0,
  tags: [],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'b58e90c0-1965-49da-a68f-c78bada847a2',
  name: 'Ratchet & Clank 3: Up Your Arsenal',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Ratchet_%26_Clank:_Up_Your_Arsenal',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '8f415f54-5b0c-416e-94aa-169813035d9a',
  name: 'Ratchet & Clank 4: Deadlocked',
  receiptLocation: 'Shadow of the Colossus',
  url: 'https://en.wikipedia.org/wiki/Ratchet:_Deadlocked',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '47fac8d7-2fdb-4ce5-b409-4da8521d306b',
  name: 'Ratchet & Clank 5: Size Matters',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Ratchet_%26_Clank:_Size_Matters',
  price: 0,
  tags: [],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'db6fbb78-f6dd-45eb-9e42-308915558c72',
  name: 'Rogue Galaxy',
  receiptLocation: 'ZHP',
  url: 'https://en.wikipedia.org/wiki/Rogue_Galaxy',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '68b2c1b0-8a3f-4e0a-b250-6cdc6225e656',
  name: 'Sakura Wars: So Long, My Love',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Sakura_Wars:_So_Long,_My_Love',
  price: 0,
  tags: [],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '98cf3178-3fee-4016-af37-a4bcf76134af',
  name: 'Shadow of the Colossus',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Shadow_of_the_Colossus',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '4ca2d88a-549d-4a47-962b-60328e010f2e',
  name: 'Shin Megami Tensei: Digital Devil Saga',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Shin_Megami_Tensei:_Digital_Devil_Saga',
  price: 0,
  tags: ['smt', 'dds'],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '87581553-5f5a-4170-827d-b37650d1b3b9',
  name: 'Shin Megami Tensei: Digital Devil Saga 2',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Shin_Megami_Tensei:_Digital_Devil_Saga',
  price: 0,
  tags: ['smt', 'dds2'],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '20127077-0515-4b28-9b04-d1f687940b2f',
  name: 'Shin Megami Tensei: Devil Summoner Raidou Kuzunoha vs. the Soulless Army',
  receiptLocation: 'Shin Megami Tensei: Digital Devil Saga 2',
  url: 'https://en.wikipedia.org/wiki/Devil_Summoner:_Raidou_Kuzunoha_vs._The_Soulless_Army',
  price: 0,
  tags: ['smt'],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '0c61b51c-d311-42d7-a95a-a3f582a9c768',
  name: 'Shin Megami Tensei: Devil Summoner 2 Raidou Kuzunoha vs. King Abaddon',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Devil_Summoner_2:_Raidou_Kuzunoha_vs._King_Abaddon',
  price: 0,
  tags: ['smt'],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '6e261031-72fd-4925-aff7-3f7b9590ca0c',
  name: 'Shin Megami Tensei III: Nocturne',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Shin_Megami_Tensei:_Nocturne',
  price: 0,
  tags: ['smt3'],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '7985cc39-2848-4359-ab2b-e776cfc0553a',
  name: 'The Simpsons: Hit & Run',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/The_Simpsons:_Hit_%26_Run',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '98b1b937-ff3d-4a0a-bc40-8be9c6759c5b',
  name: 'Sly Cooper and the Thievius Raccoonus',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Sly_Cooper_and_the_Thievius_Raccoonus',
  price: 0,
  tags: [],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '44693f11-c6b0-4650-b926-4c4d24a39b54',
  name: 'Sly 2: Band of Thieves',
  receiptLocation: 'Sly Cooper and the Thievius Raccoonus',
  url: 'https://en.wikipedia.org/wiki/Sly_2:_Band_of_Thieves',
  price: 0,
  tags: ['cooper'],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'adb93b6b-8d41-4a36-a1ae-590c8ab7b82d',
  name: 'Sly 3: Honor Among Thieves',
  receiptLocation: 'Sly Cooper and the Thievius Raccoonus',
  url: 'https://en.wikipedia.org/wiki/Sly_3:_Honor_Among_Thieves',
  price: 0,
  tags: ['cooper'],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'afa94013-721f-43a4-835f-df9a19cba28e',
  name: 'Soul Calibur III',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Soulcalibur_III',
  price: 0,
  tags: ['3'],
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '571b450b-e02b-4471-b1f6-ba4f0bcefa20',
  name: 'Star Ocean: Till the End of Time',
  receiptLocation: '(Toyratt)',
  url: 'https://en.wikipedia.org/wiki/Star_Ocean:_Till_the_End_of_Time',
  price: 0,
  tags: [],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '527cd327-ffb6-4455-b027-1a364020f30c',
  name: 'Suikoden III',
  receiptLocation: 'Phantom Brave',
  url: 'https://en.wikipedia.org/wiki/Suikoden_III',
  price: 0,
  tags: ['3'],
  extras: [],
  played: true,
  completed: true,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '16524398-22bb-4fc0-b8a3-d29eb249cba0',
  name: 'Suikoden IV',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Suikoden_IV',
  price: 0,
  tags: ['4'],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'c45f0e16-1319-4f5a-81f2-a2dfb62b11f8',
  name: 'Suikoden V',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Suikoden_V',
  price: 0,
  tags: ['5'],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '9eca22a3-94e6-4ab3-9fbe-3b219ed8aac3',
  name: 'Suikoden Tactics',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Suikoden_Tactics',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'ff4fb749-0919-483f-8000-068235818127',
  name: 'Super Dragon Ball Z',
  receiptLocation: 'Dragon Ball Z Budokai 2',
  url: 'https://en.wikipedia.org/wiki/Super_Dragon_Ball_Z',
  price: 0,
  tags: ['dbz'],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '612cf36b-f266-475b-aafe-42f0c800e91c',
  name: 'Tales of the Abyss',
  receiptLocation: 'Phantom Brave',
  url: 'https://en.wikipedia.org/wiki/Tales_of_the_Abyss',
  price: 0,
  tags: ['toa'],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '66b0a53c-0c97-46b4-81f3-af17e2eab7fd',
  name: 'Tales of Legendia',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Tales_of_Legendia',
  price: 0,
  tags: ['tol'],
  extras: ['Guidebook'],
  played: true,
  completed: true,
  favourite: true,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '20306811-676e-438e-80d2-b6e673d31dc5',
  name: 'Tony Hawk\'s  American Wasteland',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Tony_Hawk%27s_American_Wasteland',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: true,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '83beea27-b148-4a28-9bb9-55f2d6e4ee53',
  name: 'Turok: Evolution',
  receiptLocation: 'Grand Theft Auto: Vice City',
  url: 'https://en.wikipedia.org/wiki/Turok:_Evolution',
  price: 0,
  tags: [],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'f64a6507-23ea-4fa9-9ca3-8234640b41fb',
  name: 'Viewtiful Joe',
  receiptLocation: 'Grand Theft Auto: Vice City',
  url: 'https://en.wikipedia.org/wiki/Viewtiful_Joe',
  price: 0,
  tags: [],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '04e1acd8-28d7-4892-9fde-c147495403cf',
  name: 'Wild Arms 3',
  receiptLocation: '(Toyratt)',
  url: 'https://en.wikipedia.org/wiki/Wild_Arms_3',
  price: 0,
  tags: [],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '36e5bac7-106e-4e36-9cc5-fcf36f61c0cf',
  name: 'Wild Arms 4',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Wild_Arms_4',
  price: 0,
  tags: [],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '3cfb358c-a7d9-470e-8025-7d8ca9c34021',
  name: 'Wild Arms 5',
  receiptLocation: '(Mac Game Guy)',
  url: 'https://en.wikipedia.org/wiki/Wild_Arms_5',
  price: 0,
  tags: [],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'f7b325cb-b307-4e8c-98cb-29b304259550',
  name: 'Xenosaga Episode I: Der Wille zur Macht',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Xenosaga_Episode_I',
  price: 0,
  tags: ['1'],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '12bd995d-d61a-46d6-9c99-52908d999e7d',
  name: 'Xenosaga Episode II: Jenseits von Gut und Bose',
  receiptLocation: 'Tales of Legendia',
  url: 'https://en.wikipedia.org/wiki/Xenosaga_Episode_II',
  price: 0,
  tags: ['2'],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '1755e4d8-a5a6-43c1-ba74-8a470869ef13',
  name: 'Xenosaga Episode III: Also Sprach Zarathustra',
  receiptLocation: '(Mac Game Guy)',
  url: 'https://en.wikipedia.org/wiki/Xenosaga_Episode_III',
  price: 0,
  tags: ['3'],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '55e32cdb-ca04-4b20-8b9f-36e0acca34c0',
  name: 'Ys: The Ark of Napishtim',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Ys_VI:_The_Ark_of_Napishtim',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}]

export default {
  id: '3e29eafa-2268-4007-83ae-00a0d5136f68',
  name: 'PS2 (PlayStation 2)',
  index: 11,
  systems,
  cables,
  accessories,
  controllers,
  games,
}
