const systems = [{
  id: '759e3751-3e6f-4fed-a46e-f1dc1b78dd35',
  color: 'Black',
  description: '',
  borrowedInFrom: '',
  borrowedOutTo: '',
}]

const cables = ['Power', 'HDMI']

const accessories = []

const controllers = ['Black DualShock 3 x2', 'Deep Red DualShock 3']

const games = [{
  id: '87b08fcb-123c-42b0-8ad9-18c57ac1b965',
  name: 'Assassin\'s Creed',
  receiptLocation: 'Disgaea 3: Absence of Justice',
  url: 'https://en.wikipedia.org/wiki/Assassin%27s_Creed_(video_game)',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '9d7d7bce-109a-4baa-91de-fb1812ded026',
  name: 'Assassin\'s Creed II',
  receiptLocation: 'Disgaea 3: Absence of Justice',
  url: 'https://en.wikipedia.org/wiki/Assassin%27s_Creed_II',
  price: 0,
  tags: ['2'],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'fc59a251-cdc4-495f-a632-0168716e5dc9',
  name: 'Assassin\'s Creed: Revelations',
  receiptLocation: 'Disgaea 3: Absence of Justice',
  url: 'https://en.wikipedia.org/wiki/Assassin%27s_Creed:_Revelations',
  price: 0,
  tags: [],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '1e1b43b6-0d6d-4fde-a2f4-01d87dcc6cff',
  name: 'BioShock',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/BioShock',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'af2c8ebe-db5a-477a-bda6-be8079a6eb5a',
  name: 'BioShock 2',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/BioShock_2',
  price: 0,
  tags: [],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '0491e6f0-abac-4b69-8556-6000913a3042',
  name: 'Castle Crashers',
  receiptLocation: 'PSN',
  url: 'https://en.wikipedia.org/wiki/Castle_Crashers',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: true,
  favourite: true,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '14467b7b-51d3-4985-a6b1-65957bbef140',
  name: 'Crash Bandicoot',
  receiptLocation: 'PSN',
  url: 'https://en.wikipedia.org/wiki/Crash_Bandicoot_(video_game)',
  price: 6,
  tags: [],
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '13762fa5-0240-484c-b3b9-b2d8247961a3',
  name: 'Disgaea 3: Absence of Justice',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Disgaea_3',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'b7d5924d-cf91-46b5-93d3-4d44794cf672',
  name: 'Disgaea 4: A Promise Unforgotten',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Disgaea_4',
  price: 0,
  tags: [],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '6eefb615-0be4-4cf2-afb5-ea2e5982d8c2',
  name: 'Eternal Sonata',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Eternal_Sonata',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: true,
  favourite: true,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '8805fbc4-0d42-4fb5-9b1f-11ee2ef4feff',
  name: 'Explodemon',
  receiptLocation: 'PSN',
  url: 'https://en.wikipedia.org/wiki/Explodemon',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'a504c7ff-b95d-46a9-826c-996ecff609d3',
  name: 'Explodemon!',
  receiptLocation: 'PSN',
  url: 'https://en.wikipedia.org/wiki/Explodemon',
  price: 10,
  tags: [],
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '4a54e8bb-92d9-4ec7-bb9b-808417e7032c',
  name: 'Fairy Fencer F',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Fairy_Fencer_F',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: true,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '8361887b-4c3c-41e6-a396-5f328f5ca152',
  name: 'Final Fantasy X/X-2 HD Remaster',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Final_Fantasy_X/X-2_HD_Remaster',
  price: 0,
  tags: ['ffx', 'ffx-2', 'ff10', 'ff10-2'],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '84c5bf39-b68f-41e7-9c0a-1a10ac69ebbe',
  name: 'Final Fantasy XIII',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Final_Fantasy_XIII',
  price: 0,
  tags: ['ffxiii', 'ff13'],
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'ad357d58-0c1c-409b-810d-7b909f06bbcb',
  name: 'Final Fantasy XIII-2',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Final_Fantasy_XIII-2',
  price: 0,
  tags: ['ffxiii-2', 'ff13-2'],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'b1a53277-5e0e-4619-8dda-a0d147ed5b3d',
  name: 'Heavy Rain',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Heavy_Rain',
  price: 0,
  tags: [],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '7bbd231e-a1de-40cf-a333-3d60d265f07a',
  name: 'Jak and Daxter Collection',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Jak_and_Daxter_Collection',
  price: 0,
  tags: [],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'c004e921-2ded-4c29-bf6a-98234a2041b7',
  name: 'Journey',
  receiptLocation: 'PSN',
  url: 'https://en.wikipedia.org/wiki/Journey_(2012_video_game)',
  price: 15,
  tags: [],
  extras: [],
  played: true,
  completed: true,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '830cf34d-1150-4f03-b72a-ed0d03424199',
  name: 'Journey',
  receiptLocation: 'PSN',
  url: 'https://en.wikipedia.org/wiki/Journey_(2012_video_game)',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: true,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '2be72f4e-3407-405a-af71-122850a832a0',
  name: 'Lightning Returns: Final Fantasy XIII',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Lightning_Returns:_Final_Fantasy_XIII',
  price: 0,
  tags: ['ffxiii', 'ff13'],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '83181fa9-886b-437c-8d0c-982f46b8f5e6',
  name: 'Limbo',
  receiptLocation: 'PSN',
  url: 'https://en.wikipedia.org/wiki/Limbo_(video_game)',
  price: 15,
  tags: [],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'bdaa975a-bd50-4f51-b742-713b426354e4',
  name: 'Limbo',
  receiptLocation: 'PSN',
  url: 'https://en.wikipedia.org/wiki/Limbo_(video_game)',
  price: 0,
  tags: [],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '500dde25-6a61-4f0a-8ea2-23b5b572c156',
  name: 'Okami HD',
  receiptLocation: 'PSN',
  url: 'https://en.wikipedia.org/wiki/%C5%8Ckami',
  price: 14,
  tags: [],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '2376fb34-3ec8-412b-9793-b81d1b753874',
  name: 'Record of Agarest War 2',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Record_of_Agarest_War_2',
  price: 0,
  tags: [],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '0d4727a7-0a13-4cac-bab5-56a65fed3d4e',
  name: 'Scott Pilgrim vs. the World: The Game',
  receiptLocation: 'PSN',
  url: 'https://en.wikipedia.org/wiki/Scott_Pilgrim_vs._the_World:_The_Game',
  price: 10,
  tags: [],
  extras: [],
  played: true,
  completed: true,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '0bc7ef79-7538-46fb-98a3-82b6186b6c8f',
  name: 'Scott Pilgrim vs. The World: The Game',
  receiptLocation: 'PSN',
  url: 'https://en.wikipedia.org/wiki/Scott_Pilgrim_vs._the_World:_The_Game',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '8ebb0c85-c3ba-42f1-bf10-aca930842b9c',
  name: 'Spyro the Dragon',
  receiptLocation: 'PSN',
  url: 'https://en.wikipedia.org/wiki/Spyro_the_Dragon',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '3df936f0-2257-4845-989d-71a18e6c6de1',
  name: 'Spyro Year of the Dragon',
  receiptLocation: 'PSN',
  url: 'https://en.wikipedia.org/wiki/Spyro:_Year_of_the_Dragon',
  price: 6,
  tags: [],
  extras: [],
  played: true,
  completed: true,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '4b28ec46-a75f-4442-8620-2e5d249b2807',
  name: 'Star Ocean: The Last Hope',
  receiptLocation: 'Heavy Rain',
  url: 'https://en.wikipedia.org/wiki/Star_Ocean:_The_Last_Hope',
  price: 0,
  tags: [],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '1eeff4aa-09f3-4bdc-8e39-f81bfaba2fb4',
  name: 'Tales of Graces f',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Tales_of_Graces',
  price: 0,
  tags: ['tog'],
  extras: [],
  played: true,
  completed: true,
  favourite: true,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '20c662dc-dbcf-46f0-884a-97d3d2dc9186',
  name: 'Tales of Xillia',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Tales_of_Xillia',
  price: 0,
  tags: ['tox'],
  extras: [],
  played: true,
  completed: true,
  favourite: true,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '57b2fd09-5f3e-4893-ab01-6e3734a8f271',
  name: 'Tales of Xillia 2',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Tales_of_Xillia_2',
  price: 0,
  tags: ['tox2'],
  extras: ['Guidebook'],
  played: true,
  completed: true,
  favourite: true,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'c0fe86bf-52f2-4090-be2e-b3296ba3661f',
  name: 'You Don\'t Know Jack',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/You_Don%27t_Know_Jack_(2011_video_game)',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}]

export default {
  id: '85b6c75e-6101-4e51-9e17-07e6beecffb5',
  name: 'PS3 (PlayStation 3)',
  index: 12,
  systems,
  cables,
  accessories,
  controllers,
  games,
}
