const systems = []

const cables = []

const accessories = []

const controllers = []

const games = [{
  id: '0491e6f0-abac-4b69-8556-6000913a3042',
  name: 'Castle Crashers',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Castle_Crashers',
  price: 0,
  extras: [],
  played: true,
  completed: true,
  favourite: true,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '8805fbc4-0d42-4fb5-9b1f-11ee2ef4feff',
  name: 'Explodemon',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Explodemon',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '830cf34d-1150-4f03-b72a-ed0d03424199',
  name: 'Journey',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Journey_(2012_video_game)',
  price: 0,
  extras: [],
  played: true,
  completed: true,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'bdaa975a-bd50-4f51-b742-713b426354e4',
  name: 'Limbo',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Limbo_(video_game)',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '500dde25-6a61-4f0a-8ea2-23b5b572c156',
  name: 'Okami',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/%C5%8Ckami',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '0bc7ef79-7538-46fb-98a3-82b6186b6c8f',
  name: 'Scott Pilgrim vs. The World: The Game',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Scott_Pilgrim_vs._the_World:_The_Game',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '8ebb0c85-c3ba-42f1-bf10-aca930842b9c',
  name: 'Spyro the Dragon',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Spyro_the_Dragon',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}]

export default {
  id: 'fc345d35-637b-4528-9589-c5b90dc6fa12',
  name: 'PS3 (PlayStation 3) Store',
  systems,
  cables,
  accessories,
  controllers,
  games,
}
