const systems = [{
  id: '18423648-2995-4c77-893a-605830f88ac6',
  color: 'Black',
  description: '',
  borrowedInFrom: '',
  borrowedOutTo: '',
}]

const cables = ['Power', 'HDMI']

const accessories = []

const controllers = ['Jet Black DualShock 4', 'Magma Red DualShock 4']

const games = [{
  id: '0eed1bbb-343b-4e1e-9b77-ac4c0dfcc03a',
  name: 'Dragon Quest XI: Echoes of an Elusive Age',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Dragon_Quest_XI',
  price: 0,
  tags: [],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'eed817c6-a2c4-4937-82c0-cc9cd4179495',
  name: 'Horizon Zero Dawn',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Horizon_Zero_Dawn',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: true,
  favourite: true,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'f23a44e1-c914-4002-90bc-986ebe0c5ccd',
  name: 'Horizon Zero Dawn: The Frozen Wilds',
  receiptLocation: 'PSN',
  url: 'https://en.wikipedia.org/wiki/Horizon_Zero_Dawn#The_Frozen_Wilds',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: true,
  favourite: true,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '28b6d214-68de-4e7d-acb8-88ac68c2421b',
  name: 'I Am Setsuna',
  receiptLocation: 'PSN',
  url: 'https://en.wikipedia.org/wiki/I_Am_Setsuna',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '663b8bad-0271-4d9f-a3cc-cf0b524b5ac2',
  name: 'Spyro Reignited Trilogy',
  receiptLocation: 'PSN',
  url: 'https://en.wikipedia.org/wiki/Spyro_Reignited_Trilogy',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '7ed76a8b-1e02-4008-a5b5-efa91dc9bd0a',
  name: 'Tales of Berseria',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Tales_of_Berseria',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: true,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'c1e2e272-59f4-46f2-8f82-42e872b2aad1',
  name: 'Tales of Zestiria',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Tales_of_Zestiria',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: true,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'f0353e4e-49a9-49cc-abcd-670863e3e503',
  name: 'The Witcher 3: Wild Hunt',
  receiptLocation: 'PSN',
  url: 'https://en.wikipedia.org/wiki/The_Witcher_3:_Wild_Hunt',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: true,
  favourite: true,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '62a57f50-5297-4867-aa03-cac968a380dc',
  name: 'The Witcher 3: Wild Hunt - Hearts of Stone',
  receiptLocation: 'PSN',
  url: 'https://en.wikipedia.org/wiki/The_Witcher_3:_Wild_Hunt_%E2%80%93_Hearts_of_Stone',
  price: 0,
  tags: [],
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '455ffcbb-ca20-4c41-a9c9-f9a33f1c12bb',
  name: 'The Witcher 3: Wild Hunt - Blood and Wine',
  receiptLocation: 'PSN',
  url: 'https://en.wikipedia.org/wiki/The_Witcher_3:_Wild_Hunt_%E2%80%93_Blood_and_Wine',
  price: 0,
  tags: [],
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}]

export default {
  id: '9586b04a-3d6b-4af9-972c-dfdc0f610d52',
  name: 'PS4 (PlayStation 4)',
  index: 13,
  systems,
  cables,
  accessories,
  controllers,
  games,
}
