const systems = [{
  id: 'e71a3c50-6719-4d8b-977f-3dda19e18472',
  color: 'Piano Black',
  description: 'PSP-3000',
  borrowedInFrom: '',
  borrowedOutTo: '',
}]

const cables = ['Charger']

const accessories = []

const controllers = []

const games = [{
  id: '5dc232ca-89d2-4711-bc0b-1aea8be4469b',
  name: 'Crisis Core: Final Fantasy VII',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Crisis_Core:_Final_Fantasy_VII',
  price: 0,
  extras: [],
  played: true,
  completed: true,
  favourite: true,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'a5fedacf-d343-42a8-8a41-ae561c70239d',
  name: 'Disgaea: Afternoon of Darkness',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Disgaea:_Hour_of_Darkness#Disgaea:_Afternoon_of_Darkness',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '265ec71f-afc8-4cae-aec4-1660f705ce56',
  name: 'Disgaea 2: Dark Hero Days',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Disgaea_2#Re-releases',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '1e65480b-98ce-47da-aae5-90025b007e07',
  name: 'Dissidia 012 Final Fantasy',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Dissidia_012_Final_Fantasy',
  price: 0,
  extras: [],
  played: true,
  completed: true,
  favourite: true,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'baca2436-4a85-4d57-84a3-ce785b04d228',
  name: 'Final Fantasy Tactics: The War of the Lions',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Final_Fantasy_Tactics:_The_War_of_the_Lions',
  price: 0,
  extras: [],
  played: true,
  completed: true,
  favourite: true,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'ccb212f2-c9ee-4035-9e7b-c6420d96eca5',
  name: 'Jeanne d\'Arc',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Jeanne_d%27Arc_(video_game)',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '2ea4c598-6516-42fc-be05-994c0d0ae49d',
  name: 'Kingdom Hearts Birth by Sleep',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Kingdom_Hearts_Birth_by_Sleep',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '52e69a4f-49ff-499f-b9ac-c8567833e62c',
  name: 'Legend of Heroes: A Tear of Vermillion',
  receiptLocation: 'The Legend of Zelda: Ocarina of Time 3D',
  url: 'https://en.wikipedia.org/wiki/The_Legend_of_Heroes:_A_Tear_of_Vermillion',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '0c7e3f3e-c824-4ae5-b43e-3d5ab6ee35fd',
  name: 'Legend of Heroes: Trails in the Sky',
  receiptLocation: 'The Legend of Zelda: Ocarina of Time 3D',
  url: 'https://en.wikipedia.org/wiki/The_Legend_of_Heroes:_Trails_in_the_Sky',
  price: 0,
  extras: [],
  played: true,
  completed: true,
  favourite: true,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '653c91dd-2c80-420b-99b7-f47bb8ac3432',
  name: 'Little Big Planet',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/LittleBigPlanet_(2009_video_game)',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '9c169f34-8dcd-47f2-8660-4f8598c0482b',
  name: 'Lunar: Silver Star Harmony',
  receiptLocation: 'Naruto: Clash of Ninja',
  url: 'https://en.wikipedia.org/wiki/Lunar:_Silver_Star_Harmony',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '19deae1b-ed8a-4bda-af12-4e1c61035df8',
  name: 'Metal Gear Solid: Portable Ops Plus',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Metal_Gear_Solid:_Portable_Ops',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '18d7110f-9901-48c6-b94d-ae821cc8d7f9',
  name: 'Metal Gear Solid: Peace Walker',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Metal_Gear_Solid:_Peace_Walker',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '3e501e6e-0d76-4f95-aa01-6f3033302e73',
  name: 'Star Ocean: First Departure',
  receiptLocation: '(Flea market)',
  url: 'https://en.wikipedia.org/wiki/Star_Ocean_(video_game)#First_Departure',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '3b59d678-5050-4807-b255-40375e1bb078',
  name: 'Tactics Ogre: Let Us Cling Together',
  receiptLocation: 'Ratchet & Clank 3: Up Your Arsenal',
  url: 'https://en.wikipedia.org/wiki/Tactics_Ogre:_Let_Us_Cling_Together#PlayStation_Portable',
  price: 0,
  extras: [],
  played: true,
  completed: true,
  favourite: true,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '25f76669-c02e-435e-a01b-f898c3661dfe',
  name: 'Tales of Destiny 2',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Tales_of_Destiny_2',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'ea734440-7b1f-4b2c-a113-6b4d0e7c36cb',
  name: 'Tales of the World: Radiant Mythology',
  receiptLocation: 'Metal Gear Solid: Portable Ops Plus',
  url: 'https://en.wikipedia.org/wiki/Tales_of_the_World:_Radiant_Mythology',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'e952a5b9-05f4-4f1a-b4cc-bc73da92588c',
  name: 'Yggdra Union: We\'ll Never Fight Alone',
  receiptLocation: 'Crisis Core: Final Fantasy VII',
  url: 'https://en.wikipedia.org/wiki/Yggdra_Union',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'd74223ff-cd44-4848-9cd6-4f1c614a88fc',
  name: 'Ys I & II Chronicles',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Ys_I_%26_II#PlayStation_Portable',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '8f98aff5-2b8e-4f6f-86e6-a653970360e9',
  name: 'Ys: The Oath in Felghana',
  receiptLocation: '^',
  url: 'https://en.wikipedia.org/wiki/Ys:_The_Oath_in_Felghana',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'e019f047-b491-4c5a-b13d-f5a55a94c5f8',
  name: 'Ys Seven',
  receiptLocation: 'Disgaea 2: Dark Hero Days',
  url: 'https://en.wikipedia.org/wiki/Ys_Seven',
  price: 0,
  extras: [],
  played: true,
  completed: true,
  favourite: true,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '5063706f-be34-47e3-a862-e891cd0172d1',
  name: 'Z.H.P. Unlosing Ranger VS Darkdeath Evilman',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Z.H.P._Unlosing_Ranger_VS_Darkdeath_Evilman',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}]

export default {
  id: 'd9491814-d564-49cc-b299-ef8da1a19ea8',
  name: 'PSP (PlayStation Portable)',
  index: 14,
  systems,
  cables,
  accessories,
  controllers,
  games,
}
