const systems = [{
  id: '7df51f70-fbc5-42b0-a3ec-e9b86c3b3ff0',
  color: 'Grey',
  description: '',
  borrowedInFrom: '',
  borrowedOutTo: '',
}]

const cables = ['AV', 'Power']

const accessories = []

const controllers = ['Classic x2']

const games = [{
  id: 'f8988ac9-a083-4c44-ad3c-4a71f6bd6344',
  name: 'Breath of Fire',
  receiptLocation: 'Sonic Adventures 2',
  url: 'https://en.wikipedia.org/wiki/Breath_of_Fire',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '0a9cc0ef-5809-4798-bf2c-7a7fc2531e32',
  name: 'Champions World Class Soccer',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Champions_World_Class_Soccer',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '74732c51-b303-467c-a4ad-dfca94fab884',
  name: 'Final Fantasy II',
  receiptLocation: 'Final Fantasy X-2',
  url: 'https://en.wikipedia.org/wiki/Final_Fantasy_IV',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'd050e39c-0a4a-4ea0-bd40-154df45b686c',
  name: 'Final Fantasy III',
  receiptLocation: 'Wild Arms',
  url: 'https://en.wikipedia.org/wiki/Final_Fantasy_VI',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'b3b1edb4-81ab-40ec-af67-a2774f9a1067',
  name: 'Goof Troop',
  receiptLocation: '(Toyratt)',
  url: 'https://en.wikipedia.org/wiki/Goof_Troop_(video_game)',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '0b203596-5b2c-4b84-82a0-f394a93966c3',
  name: 'Illusion of Gaia',
  receiptLocation: 'Children of Mana',
  url: 'https://en.wikipedia.org/wiki/Illusion_of_Gaia',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'dffcc008-b274-4f91-8649-457a94670333',
  name: 'Kirby\'s Avalanche',
  receiptLocation: 'Sakura Wars',
  url: 'https://en.wikipedia.org/wiki/Kirby%27s_Avalanche',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '0c288317-fd09-4367-b05c-265a7435bae8',
  name: 'Ogre Battle: The March of the Black Queen',
  receiptLocation: 'Breath of Fire IV',
  url: 'https://en.wikipedia.org/wiki/Ogre_Battle:_The_March_of_the_Black_Queen',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '6136f196-98a7-41f6-86d2-4530e8b331b9',
  name: 'Road Runner\'s Death Valley Rally',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Road_Runner%27s_Death_Valley_Rally',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'fe6d378c-6a22-4f71-b216-e2715a432a3c',
  name: 'Secret of Mana',
  receiptLocation: 'Children of Mana',
  url: 'https://en.wikipedia.org/wiki/Secret_of_Mana',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'e75ec1f9-c887-4faa-8ecf-00f6e1cdd11a',
  name: 'Soul Blazer',
  receiptLocation: 'Sonic Adventure 2',
  url: 'https://en.wikipedia.org/wiki/Soul_Blazer',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'e48f1a49-ba94-4234-a9fc-9899d14b6acb',
  name: 'Street Fighter II: The World Warrior',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Street_Fighter_II:_The_World_Warrior',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'e4ff3a1e-762b-472f-a769-d6db6c169575',
  name: 'Super Mario All Stars',
  receiptLocation: 'Pikmin',
  url: 'https://en.wikipedia.org/wiki/Super_Mario_All-Stars',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'aefca292-0b87-4b27-a1ac-b43801bd4873',
  name: 'Super Mario Kart',
  receiptLocation: '(Silver case)',
  url: 'https://en.wikipedia.org/wiki/Super_Mario_Kart',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'b409e639-0873-4d19-b0eb-083801252e7f',
  name: 'Super Mario World',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Super_Mario_World',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '2a525e01-f18d-4544-9d61-10ac21bc3f2b',
  name: 'WWF Super Wrestlemania',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/WWF_Super_WrestleMania',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '56bff03a-8853-4c07-9d5d-665ad3cdcba9',
  name: 'Ys III: Wanderers from Ys',
  receiptLocation: 'Skies of Arcadia',
  url: 'https://en.wikipedia.org/wiki/Ys_III:_Wanderers_from_Ys',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'a67649ab-3d5c-4426-bc3d-478947be28a1',
  name: 'Zombies Ate My Neighbors',
  receiptLocation: 'Vagrant Story',
  url: 'https://en.wikipedia.org/wiki/Zombies_Ate_My_Neighbors',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}]

export default {
  id: '18110ff3-6b1a-485a-bfda-73e6b27d60e6',
  name: 'SNES',
  systems,
  cables,
  accessories,
  controllers,
  games,
}
