const systems = [{
  id: '65830a6c-e3ba-4834-b34f-5a338addf86f',
  color: '',
  description: 'Wii Virtual Console & WiiWare',
  borrowedInFrom: '',
  borrowedOutTo: '',
}]

const cables = []

const accessories = []

const controllers = []

const games = [{
  id: '4b2465ce-fd68-45d5-a7c6-08212807560e',
  name: 'Bases Loaded',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Bases_Loaded_(video_game)',
  price: 0,
  extras: [],
  played: false,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'ceaa306e-e045-419c-a22a-41c1413157f4',
  name: 'Mega Man',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Mega_Man_(video_game)',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'db0541e6-6192-468b-b3ea-e9db0c50967c',
  name: 'Mega Man 2',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Mega_Man_2',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '9633a145-2977-4737-8d3c-f884b8ab7cb6',
  name: 'Mega Man 9',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Mega_Man_9',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '165b7111-9551-42a0-91e0-06ac8745f96d',
  name: 'Mega Man 10',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Mega_Man_10',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '14677b68-317e-45fd-bc99-67fa7b0e66e7',
  name: 'Ninja Gainden',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Ninja_Gaiden_(NES_video_game)',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '59c3f130-d959-43bd-b6db-b4521e856813',
  name: 'Pokemon Snap',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Pok%C3%A9mon_Snap',
  price: 0,
  extras: [],
  played: true,
  completed: true,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'd9c17b88-100a-461d-8769-c6eaf7799aef',
  name: 'Super Mario 64',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/Super_Mario_64',
  price: 0,
  extras: [],
  played: true,
  completed: true,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: '8bd41d33-9372-48de-9233-65a36a5b8689',
  name: 'The Legend of Zelda: A Link to the Past',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/The_Legend_of_Zelda:_A_Link_to_the_Past',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}, {
  id: 'dd928ca2-dc7b-4903-9cc0-eec942485c74',
  name: 'The Legend of Zelda: Ocarina of Time',
  receiptLocation: '',
  url: 'https://en.wikipedia.org/wiki/The_Legend_of_Zelda:_Ocarina_of_Time',
  price: 0,
  extras: [],
  played: true,
  completed: false,
  favourite: false,
  borrowedInFrom: '',
  borrowedOutTo: '',
}]

export default {
  id: 'b8e2d831-9b3f-4464-94f1-a55bb7ebbcff',
  name: 'Wii Shop',
  systems,
  cables,
  accessories,
  controllers,
  games,
}
